const plans29=[
{id:'29a',day:29,time:'09:30–10:30',title:L('晚一点起床 + 早餐','Late start + breakfast','遅めに起床 + 朝食','ตื่นสายหน่อย + อาหารเช้า'),desc:L('睡够后早餐、整理行李。','Sleep in, have breakfast and pack.','ゆっくり起きて朝食・荷物整理。','ตื่นสาย กินอาหารเช้า จัดกระเป๋า'),map:'https://www.google.com/maps/search/?api=1&query=FuramaXclusive+Asoke+Bangkok',web:'https://www.furama.com/furamaxclusive/asoke/',est:'฿0 / ¥0',actual:false},
{id:'29b',day:29,time:'10:30–11:00',title:L('退房，寄存行李','Check out and store luggage','チェックアウト・荷物預け','เช็กเอาต์และฝากกระเป๋า'),desc:L('大行李留Furama。','Leave large luggage at Furama.','大きな荷物はFuramaに預ける。','ฝากกระเป๋าใหญ่ไว้ที่ Furama'),map:'https://www.google.com/maps/search/?api=1&query=FuramaXclusive+Asoke+Bangkok',web:'https://www.furama.com/furamaxclusive/asoke/',est:'฿0 / ¥0',actual:false},
{id:'29c',day:29,time:'11:00–11:45',title:L('Asoke → Wat Arun / 泰服店','Asoke → Wat Arun / costume shop','Asoke → Wat Arun / タイ衣装店','Asoke → Wat Arun / ร้านชุดไทย'),desc:L('两个人直接Grab/Bolt。','Grab/Bolt is easiest for two.','2人ならGrab/Boltが便利。','2 คนใช้ Grab/Bolt สะดวก'),map:'https://www.google.com/maps/dir/?api=1&origin=FuramaXclusive+Asoke+Bangkok&destination=Wat+Arun+Bangkok',web:'https://bolt.eu/en/cities/bangkok/',est:'฿150–250 / ¥720–1,200'},
{id:'29d',day:29,time:'11:45–12:30',title:L('换泰服 + 发型','Thai costume + hair styling','タイ衣装 + ヘアセット','ชุดไทย + ทำผม'),desc:L('郑王庙附近换装。','Change near Wat Arun.','ワット・アルン近くで着替え。','เปลี่ยนชุดใกล้วัดอรุณ'),map:'https://www.google.com/maps/search/?api=1&query=Absolute+Thai+Thai+Costume+Rental+Wat+Arun',web:'https://www.monkeytravel.com/th/en/ticket/bangkok/riverside/product/product_detail.php?product_id=1076867687',est:'฿350–1,000 / ¥1,680–4,800'},
{id:'29e',day:29,time:'12:30–14:30',title:L('Wat Arun 郑王庙｜泰服拍照','Wat Arun in Thai costume','タイ衣装でワット・アルン','วัดอรุณในชุดไทย'),desc:L('拍照和寺庙参观。','Photos and temple sightseeing.','写真と寺院見学。','ถ่ายรูปและชมวัด'),map:'https://www.google.com/maps/search/?api=1&query=Wat+Arun+Bangkok',web:'https://www.thailandtravel.or.jp/wat-arun/',est:'฿200 / ¥960'},
{id:'29f',day:29,time:'14:30–15:15',title:L('还泰服 → 过河渡船','Return costume → cross-river ferry','衣装返却 → 渡し船','คืนชุด → เรือข้ามฟาก'),desc:L('Wat Arun Pier → Tha Tien Pier，约3分钟。','Wat Arun Pier → Tha Tien Pier, about 3 minutes.','Wat Arun Pier → Tha Tien Pier、約3分。','Wat Arun Pier → Tha Tien Pier ประมาณ 3 นาที'),map:'https://www.google.com/maps/dir/?api=1&origin=Wat+Arun+Pier&destination=Tha+Tien+Pier&travelmode=walking',web:'https://thailandboat.com/bangkok/ferry-tha-tien-pier-wat-arun',est:'฿5.5 / ¥26'},
{id:'29g',day:29,time:'15:15–16:20',title:L('Wat Pho 卧佛寺','Wat Pho','ワット・ポー','วัดโพธิ์'),desc:L('第二座寺庙，参观卧佛和寺院。','Second temple: Reclining Buddha and temple grounds.','2つ目の寺院、涅槃仏と境内。','วัดที่สอง ชมพระนอนและบริเวณวัด'),map:'https://www.google.com/maps/search/?api=1&query=Wat+Pho+Bangkok',web:'https://www.watpho.com/en/contact/plan',est:'฿300 / ¥1,440'},
{id:'29h',day:29,time:'16:20–17:10',title:L('迟午餐 + 水果','Late lunch + fruit','遅めの昼食 + フルーツ','มื้อสาย + ผลไม้'),desc:L('Tha Tien一带简单吃东西。','Eat around Tha Tien.','Tha Tien周辺で食事。','กินแถว Tha Tien'),map:'https://www.google.com/maps/search/?api=1&query=Tha+Tien+Market+Bangkok',web:'https://www.google.com/maps/search/?api=1&query=Tha+Tien+Market+Bangkok',est:'฿300–800 / ¥1,440–3,840'},
{id:'29i',day:29,time:'17:10–18:00',title:L('Wat Pho → Furama取行李','Wat Pho → Furama for luggage','Wat Pho → Furamaで荷物受取','Wat Pho → Furama รับกระเป๋า'),desc:L('Grab/Bolt回Asoke。','Grab/Bolt back to Asoke.','Grab/BoltでAsokeへ。','Grab/Bolt กลับ Asoke'),map:'https://www.google.com/maps/dir/?api=1&origin=Wat+Pho+Bangkok&destination=FuramaXclusive+Asoke+Bangkok',web:'https://bolt.eu/en/cities/bangkok/',est:'฿150–250 / ¥720–1,200'},
{id:'29j',day:29,time:'18:30–19:30/20:00',title:L('Furama → DMK','Furama → DMK','Furama → DMK','Furama → DMK'),desc:L('Grab/Bolt/Taxi，预留堵车时间。','Grab/Bolt/taxi with traffic buffer.','Grab/Bolt/Taxi、渋滞時間を確保。','Grab/Bolt/Taxi เผื่อเวลารถติด'),map:'https://www.google.com/maps/dir/?api=1&origin=FuramaXclusive+Asoke+Bangkok&destination=Don+Mueang+International+Airport',web:'https://donmueang.airportthai.co.th/',est:'฿250–450 / ¥1,200–2,160'},
{id:'29k',day:29,time:'23:45',title:L('FD236｜DMK → FUK','FD236 | DMK → FUK','FD236｜DMK → FUK','FD236 | DMK → FUK'),desc:L('8月30日早晨抵达福冈。','Arrive in Fukuoka on Aug 30 morning.','8月30日朝に福岡到着。','ถึงฟุกุโอกะเช้าวันที่ 30 ส.ค.'),map:'https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport+Terminal+1',web:'https://www.airasia.com/',est:'฿0 / ¥0',actual:false}
];
const plans=[...plans26,...plans27,...plans28,...plans29];
