const L=(zh,en,ja,th)=>({zh,en,ja,th});
const plans27=[
{id:'27a',day:27,time:'07:30',title:L('Garden Cliff 早餐','Breakfast at Garden Cliff','Garden Cliffで朝食','อาหารเช้าที่ Garden Cliff'),desc:L('泳衣、防晒、现金、手机防水袋。','Swimwear, sunscreen, cash and waterproof phone pouch.','水着・日焼け止め・現金・防水スマホケース。','ชุดว่ายน้ำ กันแดด เงินสด ซองกันน้ำ'),map:'https://www.google.com/maps/search/?api=1&query=Garden+Cliff+Resort+%26+Spa+Pattaya',web:'https://gardencliffpattaya.com/restaurant.html',est:'฿0 / ¥0',actual:false},
{id:'27b',day:27,time:'08:10',title:L('酒店 → Bali Hai Pier','Hotel → Bali Hai Pier','ホテル → Bali Hai Pier','โรงแรม → Bali Hai Pier'),desc:L('Grab/Bolt去码头，目标09:00渡轮。','Grab/Bolt to the pier for the 09:00 ferry.','Grab/Boltで桟橋へ。09:00便を目標。','Grab/Bolt ไปท่าเรือเพื่อขึ้นเรือ 09:00'),map:'https://www.google.com/maps/dir/?api=1&origin=Garden+Cliff+Resort+%26+Spa+Pattaya&destination=Bali+Hai+Pier+Pattaya',web:'https://hellokohlarn.com/travel',est:'฿150–250 / ¥720–1,200'},
{id:'27c',day:27,time:'09:00',title:L('渡轮 → Tawaen Pier','Ferry → Tawaen Pier','フェリー → Tawaen Pier','เรือ → Tawaen Pier'),desc:L('公共渡轮，现场买票。','Public ferry; buy tickets on site.','公共フェリー、現地購入。','เรือสาธารณะ ซื้อตั๋วหน้างาน'),map:'https://www.google.com/maps/dir/?api=1&origin=Bali+Hai+Pier+Pattaya&destination=Tawaen+Beach+Koh+Larn',web:'https://koh-larn-thailand.com/getting-there/',est:'฿40 / ¥190'},
{id:'27d',day:27,time:'09:45–11:15',title:L('Tawaen Beach 水上项目｜找靠谱摊主','Tawaen Beach water activities | choose a reliable vendor','Tawaen Beach マリンアクティビティ｜信頼できる店を選ぶ','กิจกรรมทางน้ำที่ Tawaen Beach | เลือกร้านที่ไว้ใจได้'),desc:L('拖曳伞必玩；水上摩托 / 香蕉船二选一或现场看套餐；浮潜可选。先问清每项时长、总价、是否含沙滩椅/换衣/接送；当天海况不好就缩减项目。','Parasailing is the must-do. Add either jet ski or banana boat, or choose a good-value package on site; snorkeling is optional. Confirm duration, total price and whether beach chairs/changing/transfer are included before paying, and scale back if sea conditions are poor.','パラセーリングは必須。ジェットスキー／バナナボートはどちらか、または現地のセット内容で決定。シュノーケリングは任意。各項目の時間・総額・ビーチチェア／着替え／送迎の有無を先に確認し、海況が悪ければ減らす。','พาราเซลลิ่งเป็นกิจกรรมหลัก เลือกเจ็ตสกีหรือบานาน่าโบ๊ตอย่างใดอย่างหนึ่ง หรือดูแพ็กเกจหน้างาน สนอร์เกิลเป็นตัวเลือก ก่อนจ่ายให้ถามระยะเวลา ราคารวม และรวมเก้าอี้ชายหาด/ที่เปลี่ยนเสื้อผ้า/รับส่งหรือไม่ หากคลื่นลมไม่ดีให้ลดกิจกรรม'),map:'https://www.google.com/maps/search/?api=1&query=Tawaen+Beach+Koh+Larn',web:'https://koh-larn-thailand.com/budget/',est:'฿400–500+ / ¥1,920–2,400+'},
{id:'27e',day:27,time:'11:30–14:20',title:L('Tien Beach｜游泳 + 午餐 + 沙滩椅','Tien Beach | swimming + lunch + beach chair','Tien Beach｜海水浴 + 昼食 + ビーチチェア','Tien Beach | ว่ายน้ำ + อาหารกลางวัน + เก้าอี้ชายหาด'),desc:L('从Tawaen转去Tien后：游泳 → 午饭 → 沙滩椅休息 → 再游一会儿。中午最晒的时候以吃饭和遮阳休息为主，14:20左右开始往Na Baan Pier方向移动。','Transfer from Tawaen to Tien, then swim → lunch → rest on a beach chair → swim again. Use the hottest midday period for lunch and shade, and start moving toward Na Baan Pier around 14:20.','TawaenからTienへ移動後、海水浴 → 昼食 → ビーチチェアで休憩 → もう一度泳ぐ。日差しが最も強い昼は食事と日陰休憩を中心にし、14:20頃にNa Baan Pier方面へ移動開始。','จาก Tawaen ไป Tien แล้ว ว่ายน้ำ → อาหารกลางวัน → พักบนเก้าอี้ชายหาด → ว่ายน้ำอีกครั้ง ช่วงแดดแรงตอนเที่ยงเน้นกินข้าวและพักในร่ม และเริ่มไปทาง Na Baan Pier ราว 14:20'),map:'https://www.google.com/maps/search/?api=1&query=Tien+Beach+Koh+Larn',web:'https://koh-larn-thailand.com/beach/tien/',est:'฿330–600 / ¥1,580–2,880'},
{id:'27f',day:27,time:'14:20–16:15',title:L('Na Baan Pier → 芭提雅','Na Baan Pier → Pattaya','Na Baan Pier → パタヤ','Na Baan Pier → พัทยา'),desc:L('15:30左右公共渡轮返回，之后回酒店。','Take the public ferry back around 15:30, then return to the hotel.','15:30頃の公共フェリーで戻りホテルへ。','เรือกลับราว 15:30 แล้วกลับโรงแรม'),map:'https://www.google.com/maps/dir/?api=1&origin=Na+Baan+Pier+Koh+Larn&destination=Bali+Hai+Pier+Pattaya',web:'https://hellokohlarn.com/travel',est:'฿190–290 / ¥910–1,390'},
{id:'27g',day:27,time:'16:15–17:30',title:L('Garden Cliff 洗澡休息','Shower and rest at Garden Cliff','Garden Cliffで休憩','อาบน้ำและพักที่ Garden Cliff'),desc:L('换衣服，为晚上钓鱿鱼准备。','Shower and change for squid fishing.','シャワー・着替え。','อาบน้ำ เปลี่ยนเสื้อผ้า'),map:'https://www.google.com/maps/search/?api=1&query=Garden+Cliff+Resort+%26+Spa+Pattaya',web:'https://gardencliffpattaya.com/',est:'฿0 / ¥0',actual:false},
{id:'27h',day:27,time:'17:45–22:30',title:L('Tappia 夜钓鱿鱼','Tappia night squid fishing','Tappia 夜のイカ釣り','ตกหมึกกลางคืนที่ Tappia'),desc:L('去Bali Hai Pier后前往Tappia，海上夜景、钓鱿鱼、晚餐。','Bali Hai Pier → Tappia for night views, squid fishing and dinner.','Bali Hai PierからTappiaへ。夜景・イカ釣り・夕食。','ไป Tappia จาก Bali Hai ชมวิวกลางคืน ตกหมึก และอาหารเย็น'),map:'https://www.google.com/maps/search/?api=1&query=Tappia+Floating+Cafe+Pattaya',web:'https://www.ticket2attraction.com/discount-tickets/tappia-floating-cafe/',est:'฿700–1,200 / ¥3,360–5,760'}
];
const plans28=[
{id:'28a',day:28,time:'07:30–08:30',title:L('早餐、退房、寄存行李','Breakfast, checkout, store luggage','朝食・チェックアウト・荷物預け','อาหารเช้า เช็กเอาต์ ฝากกระเป๋า'),desc:L('大行李留Garden Cliff，只带随身包。','Leave large luggage at Garden Cliff.','大きな荷物はGarden Cliffに預ける。','ฝากกระเป๋าใหญ่ไว้ที่ Garden Cliff'),map:'https://www.google.com/maps/search/?api=1&query=Garden+Cliff+Resort+%26+Spa+Pattaya',web:'https://gardencliffpattaya.com/restaurant.html',est:'฿0 / ¥0',actual:false},
{id:'28b',day:28,time:'08:30–09:00',title:L('Garden Cliff → Shooting Park','Garden Cliff → Shooting Park','Garden Cliff → Shooting Park','Garden Cliff → Shooting Park'),desc:L('Bolt/Grab Car。','Use Bolt/Grab Car.','Bolt/Grab Car。','ใช้ Bolt/Grab Car'),map:'https://www.google.com/maps/dir/?api=1&origin=Garden+Cliff+Resort+%26+Spa+Pattaya&destination=Pattaya+Shooting+Park',web:'https://bolt.eu/en/cities/bangkok/',est:'฿180–280 / ¥860–1,340'},
{id:'28c',day:28,time:'09:00–09:45',title:L('Pattaya Shooting Park 射击','Pattaya Shooting Park','Pattaya Shooting Park 射撃','ยิงปืน Pattaya Shooting Park'),desc:L('体验约45分钟，套餐现场选择。','About 45 minutes; choose a package on site.','約45分、現地でプラン選択。','ประมาณ 45 นาที เลือกแพ็กเกจหน้างาน'),map:'https://www.google.com/maps/search/?api=1&query=Pattaya+Shooting+Park',web:'https://www.pattayashootingpark.com/',est:'฿1,000+ / ¥4,800+'},
{id:'28d',day:28,time:'09:45–10:15',title:L('Shooting Park → Elephant Village','Shooting Park → Elephant Village','Shooting Park → Elephant Village','Shooting Park → Elephant Village'),desc:L('Bolt/Grab到Pattaya Elephant Village。','Bolt/Grab to Pattaya Elephant Village.','Bolt/Grabで移動。','Bolt/Grab ไป Pattaya Elephant Village'),map:'https://www.google.com/maps/dir/?api=1&origin=Pattaya+Shooting+Park&destination=Pattaya+Elephant+Village+Pattaya',web:'https://www.thailandtravel.or.jp/pattaya-elephant-village/',est:'฿100–180 / ¥480–860'},
{id:'28e',day:28,time:'10:15–11:15',title:L('Pattaya Elephant Village｜15分钟骑象','Pattaya Elephant Village | 15-min ride','Pattaya Elephant Village｜15分象乗り','Pattaya Elephant Village | ขี่ช้าง 15 นาที'),desc:L('短程骑象，留时间拍照。','Short elephant ride with time for photos.','短時間の象乗りと写真。','ขี่ช้างระยะสั้นและถ่ายรูป'),map:'https://www.google.com/maps/search/?api=1&query=Pattaya+Elephant+Village+Pattaya',web:'https://www.thailandtravel.or.jp/pattaya-elephant-village/',est:'฿600 / ¥2,880'},
{id:'28f',day:28,time:'11:15–12:00',title:L('回Garden Cliff取行李','Return to Garden Cliff for luggage','Garden Cliffへ戻り荷物受取','กลับ Garden Cliff รับกระเป๋า'),desc:L('Bolt/Grab回酒店。','Bolt/Grab back to the hotel.','Bolt/Grabでホテルへ。','Bolt/Grab กลับโรงแรม'),map:'https://www.google.com/maps/dir/?api=1&origin=Pattaya+Elephant+Village+Pattaya&destination=Garden+Cliff+Resort+%26+Spa+Pattaya',web:'https://bolt.eu/en/cities/bangkok/',est:'฿160–260 / ¥770–1,250'},
{id:'28g',day:28,time:'12:00–14:30',title:L('Garden Cliff → FuramaXclusive Asoke｜固定价Taxi','Garden Cliff → FuramaXclusive Asoke | fixed-price taxi','Garden Cliff → FuramaXclusive Asoke｜固定料金Taxi','Garden Cliff → FuramaXclusive Asoke | แท็กซี่ราคาเหมาจ่าย'),desc:L('酒店到酒店单程车，预算฿1,200/车；预订时确认高速费等是否包含。','Hotel-to-hotel one-way transfer, budget ฿1,200/car; confirm tolls are included.','ホテル間片道、予算฿1,200/台。高速代込みか確認。','รถเที่ยวเดียวโรงแรมถึงโรงแรม งบ ฿1,200/คัน เช็กว่ารวมค่าทางด่วน'),map:'https://www.google.com/maps/dir/?api=1&origin=Garden+Cliff+Resort+%26+Spa+Pattaya&destination=FuramaXclusive+Asoke+Bangkok',web:'https://cherrytaxiservice.com/services-rates/',est:'฿1,200 / ¥5,760'},
{id:'28h0',day:28,time:'14:30–14:50',title:L('入住 FuramaXclusive Asoke｜1晚','Check in at FuramaXclusive Asoke | 1 night','FuramaXclusive Asokeチェックイン｜1泊','เช็กอิน FuramaXclusive Asoke | 1 คืน'),desc:L('办理入住、放行李。酒店已订，8月28日一晚，两人合计 ¥8,707。','Check in and leave luggage. Booked for Aug 28, one night for two people, ¥8,707 total.','チェックインして荷物を置く。8月28日の1泊、2人合計¥8,707で予約済み。','เช็กอินและฝากกระเป๋า จองวันที่ 28 ส.ค. 1 คืน 2 คน รวม ¥8,707'),map:'https://www.google.com/maps/search/?api=1&query=FuramaXclusive+Asoke+Bangkok',web:'https://www.furama.com/furamaxclusive/asoke/',est:L('已订｜1晚·2人 ¥8,707','Booked｜1 night · 2 people ¥8,707','予約済み｜1泊·2人 ¥8,707','จองแล้ว｜1 คืน · 2 คน ¥8,707'),actual:false},
{id:'28h',day:28,time:'14:50–15:20',title:L('Furama → Jim Thompson House','Furama → Jim Thompson House','Furama → Jim Thompson House','Furama → Jim Thompson House'),desc:L('放好行李后Grab/Bolt或轨道交通前往。','After dropping luggage, go by Grab/Bolt or rail.','荷物を置いてGrab/Boltまたは鉄道で移動。','ฝากกระเป๋าแล้วไปด้วย Grab/Bolt หรือรถไฟ'),map:'https://www.google.com/maps/dir/?api=1&origin=FuramaXclusive+Asoke+Bangkok&destination=Jim+Thompson+House+Museum',web:'https://jimthompsonhouse.org/visitor-information/',est:'฿100–200 / ¥480–960'},
{id:'28i',day:28,time:'15:20–16:45',title:L('Jim Thompson House','Jim Thompson House','Jim Thompson House','Jim Thompson House'),desc:L('参观主宅与庭院。','Visit the house and garden.','邸宅と庭園を見学。','เที่ยวบ้านและสวน'),map:'https://www.google.com/maps/search/?api=1&query=Jim+Thompson+House+Museum+Bangkok',web:'https://jimthompsonhouse.org/visitor-information/',est:'฿250 / ¥1,200'},
{id:'28j',day:28,time:'17:00+',title:L('Siam / BACC / CentralWorld + 晚餐水果','Siam / BACC / CentralWorld + dinner & fruit','Siam / BACC / CentralWorld + 夕食・フルーツ','Siam / BACC / CentralWorld + อาหารเย็นและผลไม้'),desc:L('晚间保持自由。','Keep the evening flexible.','夕方以降は自由行動。','ช่วงเย็นยืดหยุ่น'),map:'https://www.google.com/maps/search/?api=1&query=CentralWorld+Bangkok',web:'https://www.bacc.or.th/',est:'฿500–1,200 / ¥2,400–5,760'}
];
