const plans29=[
{id:'29a',day:29,time:'09:00–09:45',title:L('早餐 + 整理行李','Breakfast + pack','朝食 + 荷物整理','อาหารเช้า + จัดกระเป๋า'),desc:L('早餐后整理好行李，为上午出发留出时间。','Have breakfast and finish packing before heading out.','朝食後に荷物をまとめ、午前の出発準備。','กินอาหารเช้าและจัดกระเป๋าให้เรียบร้อยก่อนออกเที่ยว'),map:'https://www.google.com/maps/search/?api=1&query=FuramaXclusive+Asoke+Bangkok',web:'https://www.furama.com/furamaxclusive/asoke/',est:'฿0 / ¥0',actual:false},
{id:'29b',day:29,time:'09:45–10:00',title:L('退房，寄存行李','Check out and store luggage','チェックアウト・荷物預け','เช็กเอาต์และฝากกระเป๋า'),desc:L('大行李留在 Furama，晚上回来取。','Leave large luggage at Furama and collect it in the evening.','大きな荷物はFuramaに預け、夕方受け取る。','ฝากกระเป๋าใหญ่ไว้ที่ Furama แล้วกลับมารับช่วงเย็น'),map:'https://www.google.com/maps/search/?api=1&query=FuramaXclusive+Asoke+Bangkok',web:'https://www.furama.com/furamaxclusive/asoke/',est:'฿0 / ¥0',actual:false},
{id:'29c',day:29,time:'10:00–10:50',title:L('Furama → Wat Paknam','Furama → Wat Paknam','Furama → Wat Paknam','Furama → Wat Paknam'),desc:L('推荐 MRT：从 Sukhumvit 站坐 Blue Line 到 Bang Phai，再步行前往 Wat Paknam。','Recommended: take the MRT Blue Line from Sukhumvit to Bang Phai, then walk to Wat Paknam.','MRT推奨：Sukhumvit駅からBlue LineでBang Phaiへ行き、Wat Paknamまで徒歩。','แนะนำ MRT: จาก Sukhumvit นั่งสาย Blue Line ไป Bang Phai แล้วเดินไป Wat Paknam'),map:'https://www.google.com/maps/dir/?api=1&origin=FuramaXclusive+Asoke+Bangkok&destination=Wat+Paknam+Phasi+Charoen+Bangkok&travelmode=transit',web:'https://www.thailandtravel.or.jp/wat-paknam/',est:'฿80–120 / ¥380–580'},
{id:'29c1',day:29,time:'10:50–11:50',title:L('Wat Paknam 水门寺','Wat Paknam Phasi Charoen','Wat Paknam Phasi Charoen','วัดปากน้ำ ภาษีเจริญ'),desc:L('参观金色大佛、白色大佛塔与塔内绿色玻璃佛塔。','See the giant golden Buddha, the white pagoda and the green glass stupa inside.','黄金の大仏、白い仏塔、内部の緑色ガラス仏塔を見学。','ชมพระพุทธรูปทองคำองค์ใหญ่ เจดีย์สีขาว และเจดีย์แก้วสีเขียวภายใน'),map:'https://www.google.com/maps/search/?api=1&query=Wat+Paknam+Phasi+Charoen+Bangkok',web:'https://www.thailandtravel.or.jp/wat-paknam/',est:'฿0 / ¥0',actual:false},
{id:'29c2',day:29,time:'11:50–12:15',title:L('Wat Paknam → Wat Arun 一带','Wat Paknam → Wat Arun area','Wat Paknam → Wat Arun周辺','Wat Paknam → ย่าน Wat Arun'),desc:L('两个人直接 Grab/Bolt，先到郑王庙附近吃午饭。','Take Grab/Bolt for two and go straight to the Wat Arun area for lunch.','2人でGrab/Boltを利用し、まずWat Arun周辺で昼食。','ใช้ Grab/Bolt สำหรับ 2 คน ไปย่าน Wat Arun เพื่อกินมื้อกลางวันก่อน'),map:'https://www.google.com/maps/dir/?api=1&origin=Wat+Paknam+Phasi+Charoen+Bangkok&destination=Khao+Moo+Tod+Wat+Arun+Bangkok&travelmode=driving',web:'https://bolt.eu/en/cities/bangkok/',est:'฿80–150 / ¥380–720'},
{id:'29c3',day:29,time:'12:15–12:45',title:L('午饭｜Khao Moo Tod Wat Arun','Lunch | Khao Moo Tod Wat Arun','昼食｜Khao Moo Tod Wat Arun','มื้อกลางวัน | Khao Moo Tod Wat Arun'),desc:L('换泰服和做发型前先吃。优先炸猪肉盖饭 + 蛋 + 冰饮，简单、快，控制在约30分钟。地址：135/1 Arun Amarin Road，Wat Arun 一带。','Eat before changing into Thai costume and styling hair. Fried pork rice with egg and a cold drink is the easy choice; keep lunch to about 30 minutes. 135/1 Arun Amarin Road near Wat Arun.','タイ衣装とヘアセットの前に昼食。揚げ豚のせご飯＋卵＋冷たい飲み物を目安に、約30分で軽く食べる。Wat Arun近くの135/1 Arun Amarin Road。','กินก่อนเปลี่ยนชุดไทยและทำผม แนะนำข้าวหมูทอด + ไข่ + เครื่องดื่มเย็น ใช้เวลาประมาณ 30 นาที อยู่ที่ 135/1 Arun Amarin Road ใกล้ Wat Arun'),map:'https://www.google.com/maps/search/?api=1&query=Khao+Moo+Tod+Wat+Arun+Bangkok',web:'https://www.tripadvisor.com/Restaurant_Review-g293916-d14175680-Reviews-Khao_Moo_Tod_Wat_Arun-Bangkok.html',est:'฿150–300 / ¥720–1,440'},
{id:'29d',day:29,time:'12:45–13:30',title:L('换泰服 + 发型｜3家到场再选','Thai costume + hair | choose among 3 on the day','タイ衣装 + ヘアセット｜当日3店から選択','ชุดไทย + ทำผม | เลือกจาก 3 ร้านวันจริง'),desc:L('Wat Arun附近保留3家备选：Thai Glam Studio、Bestie Thai Costume、Absolute Thai。当天先看衣服实物、排队、价格和Google评价再决定。两人基础/中档泰服+发型先按约฿800–3,000规划；高档服装、完整妆发或专业摄影会更高，另行确认。下方提供每家Google Maps和官网/预订入口。','Keep three options near Wat Arun: Thai Glam Studio, Bestie Thai Costume and Absolute Thai. Decide after checking the actual outfits, queues, prices and Google reviews. For two people, plan about ฿800–3,000 for basic/mid-range costume + hair; premium outfits, full makeup/hair or professional photography can cost more. Google Maps and official/booking links are shown below.','Wat Arun周辺でThai Glam Studio、Bestie Thai Costume、Absolute Thaiの3店を候補として残す。当日の衣装、待ち時間、料金、Google口コミを見て決定。2人分の基本〜中価格帯の衣装＋ヘアは約฿800–3,000を目安とし、上位衣装、フルメイク、プロ撮影は別途。下にGoogle Mapsと公式/予約リンクを表示。','เก็บ 3 ร้านใกล้ Wat Arun ได้แก่ Thai Glam Studio, Bestie Thai Costume และ Absolute Thai แล้วเลือกวันจริงหลังดูชุด คิว ราคา และรีวิว Google งบพื้นฐาน/ระดับกลางสำหรับชุด+ทำผม 2 คนประมาณ ฿800–3,000 ชุดพรีเมียม แต่งหน้าครบ หรือช่างภาพมืออาชีพจะสูงกว่านี้ ลิงก์ Google Maps และเว็บ/จองอยู่ด้านล่าง'),map:'https://www.google.com/maps/search/?api=1&query=Thai+costume+rental+Wat+Arun+Bangkok',web:'https://www.google.com/maps/search/?api=1&query=Thai+costume+rental+Wat+Arun+Bangkok',est:'฿800–3,000 / ¥3,840–14,400'},
{id:'29e',day:29,time:'13:30–15:15',title:L('Wat Arun 郑王庙｜泰服拍照','Wat Arun in Thai costume','タイ衣装でワット・アルン','วัดอรุณในชุดไทย'),desc:L('换好泰服后直接拍照和参观寺庙。若临时加专业摄影，以店家当天报价为准。','Go straight to Wat Arun for photos and sightseeing after changing. If you add a professional photographer, use the shop’s current quote.','着替え後そのままWat Arunで写真撮影と寺院見学。プロ撮影を追加する場合は当日の店舗料金を確認。','เปลี่ยนชุดเสร็จแล้วไปถ่ายรูปและชมวัดอรุณต่อ หากเพิ่มช่างภาพมืออาชีพให้เช็กราคาปัจจุบันของร้าน'),map:'https://www.google.com/maps/search/?api=1&query=Wat+Arun+Bangkok',web:'https://www.thailandtravel.or.jp/wat-arun/',est:'฿200 / ¥960'},
{id:'29f',day:29,time:'15:15–15:45',title:L('还泰服 → 过河渡船','Return costume → cross-river ferry','衣装返却 → 渡し船','คืนชุด → เรือข้ามฟาก'),desc:L('还衣服后到 Wat Arun Pier，坐渡船到 Tha Tien Pier。','Return the costume, then take the ferry from Wat Arun Pier to Tha Tien Pier.','衣装返却後、Wat Arun PierからTha Tien Pierへ渡し船。','คืนชุดแล้วขึ้นเรือจาก Wat Arun Pier ไป Tha Tien Pier'),map:'https://www.google.com/maps/dir/?api=1&origin=Wat+Arun+Pier&destination=Tha+Tien+Pier&travelmode=walking',web:'https://thailandboat.com/bangkok/ferry-tha-tien-pier-wat-arun',est:'฿5.5 / ¥26'},
{id:'29g',day:29,time:'15:45–16:45',title:L('Wat Pho 卧佛寺','Wat Pho','ワット・ポー','วัดโพธิ์'),desc:L('参观卧佛和寺院。','See the Reclining Buddha and temple grounds.','涅槃仏と境内を見学。','ชมพระนอนและบริเวณวัด'),map:'https://www.google.com/maps/search/?api=1&query=Wat+Pho+Bangkok',web:'https://www.watpho.com/en/contact/plan',est:'฿300 / ¥1,440'},
{id:'29h',day:29,time:'16:45–17:10',title:L('水果 + 冰饮休息','Fruit + cold drink break','フルーツ + 冷たい飲み物','ผลไม้ + เครื่องดื่มเย็น'),desc:L('Tha Tien一带补水果和饮料，不再安排第二顿正式午饭。','Grab some fruit and a drink around Tha Tien; no second full lunch is planned.','Tha Tien周辺でフルーツと飲み物。2回目の本格的な昼食は入れない。','กินผลไม้และเครื่องดื่มแถว Tha Tien โดยไม่จัดมื้อกลางวันเต็มอีกมื้อ'),map:'https://www.google.com/maps/search/?api=1&query=Tha+Tien+Market+Bangkok',web:'https://www.google.com/maps/search/?api=1&query=Tha+Tien+Market+Bangkok',est:'฿100–300 / ¥480–1,440'},
{id:'29i',day:29,time:'17:10–18:00',title:L('Wat Pho → Furama取行李','Wat Pho → Furama for luggage','Wat Pho → Furamaで荷物受取','Wat Pho → Furama รับกระเป๋า'),desc:L('Grab/Bolt回Asoke。','Grab/Bolt back to Asoke.','Grab/BoltでAsokeへ。','Grab/Bolt กลับ Asoke'),map:'https://www.google.com/maps/dir/?api=1&origin=Wat+Pho+Bangkok&destination=FuramaXclusive+Asoke+Bangkok',web:'https://bolt.eu/en/cities/bangkok/',est:'฿150–250 / ¥720–1,200'},
{id:'29j',day:29,time:'18:30–19:30/20:00',title:L('Furama → DMK','Furama → DMK','Furama → DMK','Furama → DMK'),desc:L('Grab/Bolt/Taxi，预留堵车时间。','Grab/Bolt/taxi with traffic buffer.','Grab/Bolt/Taxi、渋滞時間を確保。','Grab/Bolt/Taxi เผื่อเวลารถติด'),map:'https://www.google.com/maps/dir/?api=1&origin=FuramaXclusive+Asoke+Bangkok&destination=Don+Mueang+International+Airport',web:'https://donmueang.airportthai.co.th/',est:'฿250–450 / ¥1,200–2,160'},
{id:'29k',day:29,time:'23:45–次日07:05',title:L('FD236｜两人共同回程 DMK → FUK','FD236 | Return together DMK → FUK','FD236｜2人で帰国 DMK → FUK','FD236 | เดินทางกลับด้วยกัน DMK → FUK'),desc:L('8月29日23:45从DMK起飞，8月30日07:05抵达福冈。','Depart DMK at 23:45 on Aug 29 and arrive in Fukuoka at 07:05 on Aug 30.','8月29日23:45にDMKを出発し、8月30日07:05に福岡到着。','ออกจาก DMK 23:45 วันที่ 29 ส.ค. ถึงฟุกุโอกะ 07:05 วันที่ 30 ส.ค.'),map:'https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport+Terminal+1',web:'https://www.airasia.com/',est:'฿0 / ¥0',actual:false}
];
const plans=[...plans26,...plans27,...plans28,...plans29];
