/* Day 26 itinerary — single source of truth.
   The final 8/26 schedule (previously assembled by plans-a + day26-dinner-options
   + day26-evening-order at runtime) is now written here directly.
   Dinner alternatives are a formal data structure on item d26_5:
   - alternatives[]: id / name / tag / reason / price / dest / mode / google / menu
   - altKey: localStorage key that stores the selected alternative id
   - altOrigin: route origin shown when a restaurant is clicked
   Item d26_terminal21 declares routeFromAltOf:'d26_5', so its route always
   starts from the currently selected dinner restaurant. */

const T4=(zh,en,ja,th)=>({zh,en,ja,th});
const GC_NAME='Garden Cliff Resort & Spa Pattaya';
const GC_Q='Garden+Cliff+Resort+%26+Spa+Pattaya';

const DINNER_ALTS=[
  {id:'bamboo',name:'Bamboo Beach',mode:'walking',dest:'Bamboo Beach Pattaya',
   tag:T4('主计划 / 第一选择','Main plan / first choice','主計画 / 第一候補','แผนหลัก / ตัวเลือกแรก'),
   reason:T4('默认主计划：离 Garden Cliff 很近、步行可达、就在海边，价格相对轻松，也最方便晚饭后直接去 Terminal 21。适合第一天少折腾、轻松吃泰菜和部分海鲜。','Default main plan: very close to Garden Cliff, walkable and right by the sea, with friendlier prices and the simplest onward trip to Terminal 21. Best for an easy first evening with Thai food and some seafood.','デフォルトの主計画。Garden Cliffから近く徒歩圏、海辺で価格も比較的気軽。夕食後そのままTerminal 21へ向かいやすく、初日は移動を増やさずタイ料理とシーフードを楽しめる。','แผนหลักเริ่มต้น: อยู่ใกล้ Garden Cliff เดินถึง ริมทะเล ราคาสบายกว่า และไป Terminal 21 ต่อได้ง่ายที่สุด เหมาะกับคืนแรกที่อยากลดการเดินทางและกินอาหารไทยกับซีฟู้ดแบบสบาย ๆ'),
   price:'฿500–1,200 · ¥2,400–5,760',google:'https://www.google.com/maps/search/?api=1&query=Bamboo+Beach+Pattaya',menu:'https://www.facebook.com/BambooBeachPattaya/'},
  {id:'moom',name:'Moom Aroi Na Kluea',mode:'driving',dest:'Moom Aroi Na Kluea Pattaya',
   tag:T4('丰盛海鲜备用','Full seafood backup','海鮮大餐の予備','สำรองซีฟู้ดจัดเต็ม'),
   reason:T4('当天特别想认真吃一顿泰式海鲜时切换：虾、蟹、鱼、鱿鱼选择更丰富，适合把晚餐本身作为重点体验。','Switch here when you especially want a fuller Thai seafood dinner: a broader choice of prawns, crab, fish and squid, making dinner itself a main experience.','タイ式シーフードをしっかり食べたい日に切り替える候補。エビ・カニ・魚・イカの選択肢が多く、夕食そのものをメイン体験にしたい時向け。','เปลี่ยนมาร้านนี้เมื่ออยากกินซีฟู้ดไทยแบบจริงจัง มีตัวเลือกกุ้ง ปู ปลา และปลาหมึกมากกว่า เหมาะเมื่ออยากให้มื้อเย็นเป็นกิจกรรมหลัก'),
   price:'฿1,200–2,200 · ¥5,760–10,560',google:'https://www.google.com/maps/search/?api=1&query=Moom+Aroi+Na+Kluea+Pattaya',menu:'https://www.google.com/maps/search/?api=1&query=Moom+Aroi+Na+Kluea+Pattaya'},
  {id:'glass',name:'The Glass House Silver',mode:'driving',dest:'The Glass House Silver Pattaya',
   tag:T4('环境 / 拍照备用','Atmosphere / photo backup','雰囲気・写真の予備','สำรองบรรยากาศ / ถ่ายรูป'),
   reason:T4('时间充裕、想把海边度假氛围和拍照放在第一位时选：沙滩座位和玻璃屋环境更适合拍照，菜偏泰西混合。','Choose when time is ample and seaside resort atmosphere and photos matter most: beach seating and the glass-house setting are especially photogenic; the menu mixes Thai and Western.','時間に余裕があり、海辺のリゾート感と写真を優先したい日に。ビーチ席とガラスハウスの空間が写真向きで、料理はタイ×洋のミックス。','เลือกเมื่อมีเวลาและอยากเน้นบรรยากาศรีสอร์ทริมทะเลกับการถ่ายรูป ที่นั่งบนหาดและตัวร้านกระจกถ่ายรูปสวย เมนูเป็นไทยผสมตะวันตก'),
   price:'฿1,000–2,000 · ¥4,800–9,600',google:'https://www.google.com/maps/search/?api=1&query=The+Glass+House+Silver+Pattaya',menu:'https://www.glasshouse-pattaya.com/en/glasshouse-silver-menu.php'},
  {id:'chomtalay',name:'Chomtalay',mode:'walking',dest:'Chom Talay Restaurant Garden Cliff Pattaya',
   tag:T4('严重延误兜底','Serious-delay fallback','大幅遅延時の保険','สำรองเมื่อดีเลย์หนัก'),
   reason:T4('航班延误、入境很慢、堵车或到酒店已经太晚时使用：这是 Garden Cliff 酒店自己的餐厅，走几步就到，尽量保住 Terminal 21 的购物时间。注意不要和 Jomtien 的同名餐厅混淆。','Use after flight delays, slow immigration, traffic or a very late hotel arrival: this is Garden Cliff’s own restaurant a short walk away, protecting the Terminal 21 shopping window. Not the Jomtien restaurant of the same name.','フライト遅延・入国審査の遅れ・渋滞などでホテル到着がかなり遅い時の保険。Garden Cliffのホテル内レストランで徒歩すぐ、Terminal 21の買い物時間を確保できる。Jomtienの同名店と混同しないこと。','ใช้เมื่อไฟลต์ดีเลย์ ตม. ช้า รถติด หรือถึงโรงแรมดึกมาก เป็นห้องอาหารของ Garden Cliff เอง เดินไม่กี่ก้าว ช่วยรักษาเวลาช้อปที่ Terminal 21 อย่าสับสนกับร้านชื่อเดียวกันที่จอมเทียน'),
   price:'฿1,000–1,800 · ¥4,800–8,640',google:'https://www.google.com/maps/search/?api=1&query=Chom+Talay+Restaurant+Garden+Cliff+Pattaya',menu:'https://gardencliffpattaya.com/restaurant.html'}
];

const plans26 = [
{id:'d26_f1',day:26,time:'08:15–11:45',title:T4('FD237｜FUK → DMK','FD237 | FUK → DMK','FD237｜FUK → DMK','FD237 | FUK → DMK'),desc:T4('你的去程航班：福冈 08:15 起飞，11:45 抵达曼谷廊曼机场。机票金额为往返合计。','Your outbound flight: depart Fukuoka at 08:15 and arrive at Bangkok Don Mueang at 11:45. The amount shown is the round-trip fare.','あなたの往路便：福岡08:15発、バンコク・ドンムアン11:45着。表示金額は往復航空券の合計。','เที่ยวบินขาไปของคุณ: ออกจากฟุกุโอกะ 08:15 ถึงดอนเมือง 11:45 ยอดที่แสดงเป็นค่าโดยสารไป-กลับ'),map:'https://www.google.com/maps/search/?api=1&query=Fukuoka+Airport',web:'https://www.airasia.com/',est:T4('往返机票｜¥60,000 / 人','Round trip｜¥60,000 / person','往復航空券｜¥60,000 / 人','ไป-กลับ｜¥60,000 / คน'),actual:false},
{id:'d26_f2',day:26,time:'09:15–14:00',title:T4('森田航班｜NRT → DMK',"Morita's flight | NRT → DMK",'森田の便｜NRT → DMK','เที่ยวบิน Morita | NRT → DMK'),desc:T4('森田从东京成田出发，09:15 起飞、14:00 抵达 DMK。航班号待确认。机票金额为往返合计。','Morita departs Tokyo Narita at 09:15 and arrives at DMK at 14:00. Flight number to be confirmed. The amount shown is the round-trip fare.','森田は成田09:15発、DMK14:00着。便名は確認待ち。表示金額は往復航空券の合計。','Morita ออกจากนาริตะ 09:15 ถึง DMK 14:00 หมายเลขเที่ยวบินรอยืนยัน ยอดที่แสดงเป็นค่าโดยสารไป-กลับ'),map:'https://www.google.com/maps/search/?api=1&query=Narita+International+Airport',web:'https://www.airasia.com/',est:T4('往返机票｜¥60,000 / 人','Round trip｜¥60,000 / person','往復航空券｜¥60,000 / 人','ไป-กลับ｜¥60,000 / คน'),actual:false},
{id:'d26_1',day:26,time:'11:45–12:20',title:T4('抵达 DMK｜入境、取行李','Arrive at DMK | immigration & bags','DMK到着｜入国・荷物受取','ถึง DMK | ตม. และรับกระเป๋า'),desc:T4('FD237抵达后完成入境和取行李。','After FD237 arrives, clear immigration and collect luggage.','FD237到着後、入国審査と荷物受取を済ませる。','หลัง FD237 ถึง ผ่าน ตม. และรับกระเป๋า'),map:'https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport',web:'https://donmueang.airportthai.co.th/',est:'฿0 / ¥0',actual:false},
{id:'d26_snack',day:26,time:'12:20–13:40',title:T4('DMK休息 + 买两人路上吃的外带','Rest at DMK + buy takeaway for the car','DMKで休憩 + 車内用テイクアウト購入','พักที่ DMK + ซื้ออาหารกลับไปกินบนรถ'),desc:T4('机场不安排正式午餐。你先休息，并提前买两个人路上吃的外带和饮料；选择方便在车上吃、气味不重的食物。森田到达后尽快汇合出发。','Skip a sit-down airport lunch. Rest and buy takeaway food and drinks for both of you to eat in the car; choose tidy, low-odor food. Leave as soon as Morita clears arrivals.','空港では正式な昼食を取らず、休憩しながら2人分の車内用テイクアウトと飲み物を購入。車内で食べやすく匂いの強くない物を選び、森田到着後できるだけ早く出発。','ไม่กินมื้อกลางวันแบบนั่งที่สนามบิน พักและซื้ออาหารกลับพร้อมเครื่องดื่มสำหรับ 2 คนไว้กินบนรถ เลือกอาหารที่กินง่ายและกลิ่นไม่แรง แล้วออกเดินทางทันทีหลัง Morita ผ่าน ตม.'),map:'https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport+food',web:'https://donmueang.airportthai.co.th/',est:'฿300–600 / ¥1,440–2,880'},
{id:'d26_wait',day:26,time:'13:40–14:00',title:T4('DMK 休息、等森田','Rest at DMK and wait for Morita','DMKで休憩・森田待ち','พักที่ DMK และรอ Morita'),desc:T4('到到达区附近等森田，预约车保持联系。','Wait near arrivals for Morita and stay in contact with the booked driver.','到着ロビー付近で森田を待ち、予約車と連絡を取る。','รอ Morita ใกล้โถงผู้โดยสารขาเข้าและติดต่อรถที่จองไว้'),map:'https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport',web:'https://donmueang.airportthai.co.th/',est:'฿0 / ¥0',actual:false},
{id:'d26_2',day:26,time:'14:00–14:35',title:T4('森田抵达 DMK → 入境、取行李、汇合','Morita arrives at DMK → immigration, bags, meet','森田がDMK到着 → 入国・荷物受取・合流','Morita ถึง DMK → ตม. รับกระเป๋า และพบกัน'),desc:T4('森田14:00落地后尽快完成入境、取行李并汇合。目标14:35左右出到达区；实际时间取决于入境排队和行李。','After Morita lands at 14:00, clear immigration and baggage as quickly as practical. Target arrivals around 14:35; actual timing depends on queues and bags.','森田14:00到着後、入国審査・荷物受取を済ませて合流。14:35頃に到着ロビーへ出るのが目標。実際は入国審査と荷物次第。','หลัง Morita ลงเครื่อง 14:00 ผ่าน ตม. รับกระเป๋าและพบกันให้เร็วที่สุด เป้าหมายออกมาราว 14:35 เวลาจริงขึ้นอยู่กับคิว ตม. และกระเป๋า'),map:'https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport',web:'https://donmueang.airportthai.co.th/',est:'฿0 / ¥0',actual:false},
{id:'d26_lunch',day:26,time:'14:35–14:45',title:T4('汇合后直接上预约车｜路上吃外带','Meet → straight to booked car | eat takeaway en route','合流後すぐ予約車へ｜車内でテイクアウト','พบกันแล้วขึ้นรถที่จองทันที | กินอาหารบนรถ'),desc:T4('不在机场停下来吃饭。拿好外带直接去预约车，目标14:45前离开DMK；上车前确认司机是否方便车内饮食。','Do not stop for a sit-down meal. Take the takeaway straight to the booked car and aim to leave DMK by 14:45; confirm with the driver before eating in the vehicle.','空港で食事のために止まらず、テイクアウトを持ってそのまま予約車へ。14:45までのDMK出発を目標にし、車内飲食は乗車前に運転手へ確認。','ไม่หยุดกินที่สนามบิน ถืออาหารกลับไปขึ้นรถที่จองทันที เป้าหมายออกจาก DMK ก่อน 14:45 และถามคนขับก่อนกินอาหารบนรถ'),map:'https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport',web:'https://donmueang.airportthai.co.th/',est:'฿0 / ¥0',actual:false},
{id:'d26_3',day:26,time:'14:45–17:00',title:T4('DMK → Garden Cliff','DMK → Garden Cliff','DMK → Garden Cliff','DMK → Garden Cliff'),desc:T4('预约车直达Garden Cliff。目标17:00左右到酒店；遇入境慢或堵车则可能顺延到17:30以后。路上吃提前买好的外带。','Booked car straight to Garden Cliff. Target hotel arrival around 17:00, with 17:30+ possible if immigration or traffic is slow. Eat the takeaway en route.','予約車でGarden Cliffへ直行。17:00頃のホテル到着を目標とし、入国審査や渋滞で17:30以降になる可能性あり。車内でテイクアウトを食べる。','รถที่จองตรงไป Garden Cliff เป้าหมายถึงโรงแรมประมาณ 17:00 แต่อาจเป็นหลัง 17:30 หาก ตม. ช้าหรือรถติด กินอาหารที่ซื้อไว้ระหว่างทาง'),map:'https://www.google.com/maps/dir/?api=1&origin=Don+Mueang+International+Airport&destination='+GC_Q,web:'https://www.pattaya-transfer.com/dmk-to-pattaya-price.aspx',est:'฿1,499 / ¥7,200'},
{id:'d26_4',day:26,time:'17:00–17:20',title:T4('入住 Garden Cliff｜2晚','Check in at Garden Cliff | 2 nights','Garden Cliffチェックイン｜2泊','เช็กอิน Garden Cliff | 2 คืน'),desc:T4('到店后快速办理入住、放行李。酒店已订，8月26–27日两晚，两人合计 ¥21,000。入住时可顺便确认酒店往返 Terminal 21 Gate 2 的免费 Shuttle Bus 当天班次；若时间不合适就直接叫车。','Check in quickly and drop the luggage. The hotel is booked for Aug 26–27, two nights for two, ¥21,000 total. At check-in, confirm the complimentary shuttle schedule to Terminal 21 Gate 2; use a car if the timing does not fit.','到着後すぐチェックインして荷物を置く。8月26–27日2泊、2人合計¥21,000で予約済み。チェックイン時にTerminal 21 Gate 2往復の無料シャトル当日便を確認し、時間が合わなければ車で移動。','เช็กอินและวางกระเป๋าอย่างรวดเร็ว จอง 26–27 ส.ค. 2 คืน 2 คน รวม ¥21,000 ตอนเช็กอินให้ถามรอบรถรับส่งฟรีไป Terminal 21 Gate 2 หากเวลาไม่พอดีให้เรียกรถแทน'),map:'https://www.google.com/maps/search/?api=1&query='+GC_Q,web:'https://gardencliffpattaya.com/facilities.html',est:T4('已订｜2晚·2人 ¥21,000','Booked｜2 nights · 2 people ¥21,000','予約済み｜2泊·2人 ¥21,000','จองแล้ว｜2 คืน · 2 คน ¥21,000'),actual:false},
{id:'d26_5',day:26,time:'17:40–19:10',title:T4('Bamboo Beach 海边晚餐｜主计划 + 3家备用','Bamboo Beach dinner | main plan + 3 backups','Bamboo Beach 海辺ディナー｜主計画 + 3候補','มื้อเย็น Bamboo Beach | แผนหลัก + 3 ตัวสำรอง'),desc:T4('四家全部保留，默认主计划是 Bamboo Beach：离 Garden Cliff 很近、步行可达、海边、价格相对轻松，吃完直接去 Terminal 21 最省事。当天特别想吃丰盛泰式海鲜可以切换 Moom Aroi；更重视环境和拍照可选 The Glass House Silver；严重延误时用酒店内 Chomtalay 兜底。点击下方任意一家，右侧地图会显示酒店出发路线；该选择也会自动成为之后去 Terminal 21 的路线起点。目标19:10左右结束。','Keep all four. Bamboo Beach is the default main plan: very close to Garden Cliff, walkable, seaside, relatively easy on the budget, and the simplest onward trip to Terminal 21. Switch to Moom Aroi for a fuller Thai seafood dinner, The Glass House Silver for atmosphere/photos, or Chomtalay inside the hotel after a serious delay. Tap any restaurant below to preview the route from the hotel; that choice automatically becomes the start of the later Terminal 21 route. Aim to finish around 19:10.','4店すべて残す。デフォルトの主計画はBamboo Beach。Garden Cliffから近く徒歩圏、海辺で価格も比較的気軽で、食後Terminal 21へ向かう流れが最も楽。しっかりしたタイ式シーフードならMoom Aroi、雰囲気・写真重視ならThe Glass House Silver、大幅遅延時はホテル内Chomtalayに切り替える。下の店をタップするとホテルからのルートが表示され、その選択が後のTerminal 21ルートの出発点にも自動反映される。19:10頃の終了が目標。','เก็บทั้ง 4 ร้านไว้ โดย Bamboo Beach เป็นแผนหลักเริ่มต้น เพราะอยู่ใกล้ Garden Cliff เดินถึง ริมทะเล ราคาสบายกว่า และไป Terminal 21 ต่อได้ง่ายที่สุด หากอยากกินซีฟู้ดไทยจัดเต็มให้เปลี่ยนเป็น Moom Aroi เน้นบรรยากาศ/ถ่ายรูปเลือก The Glass House Silver และหากดีเลย์หนักใช้ Chomtalay ในโรงแรม แตะร้านด้านล่างเพื่อดูเส้นทางจากโรงแรม และร้านที่เลือกจะเป็นจุดเริ่มของเส้นทางไป Terminal 21 อัตโนมัติ เป้าหมายเสร็จราว 19:10'),map:'https://www.google.com/maps/dir/?api=1&origin='+GC_Q+'&destination=Bamboo+Beach+Pattaya&travelmode=walking',web:'https://www.facebook.com/BambooBeachPattaya/',est:'฿500–2,200 / ¥2,400–10,560',altKey:'d26DinnerChoice',altOrigin:GC_NAME,alternatives:DINNER_ALTS},
{id:'d26_terminal21',day:26,time:'19:20–21:35',title:T4('Terminal 21 Pattaya｜泳装 + 罩衫 + 女装','Terminal 21 Pattaya | swimwear + cover-up + womenswear','Terminal 21 Pattaya｜水着 + カバーアップ + レディース','Terminal 21 Pattaya | ชุดว่ายน้ำ + ชุดคลุม + เสื้อผ้าผู้หญิง'),desc:T4('晚餐后19:20–19:30从餐厅出发（右侧地图会按所选餐厅显示路线）。26号只解决27号格兰岛必须用的购物：先看 GENTLEWOMAN 的泳装/罩衫，再看裙子、短裤、吊带和其他女装；没找到合适泳装再看 Rip Curl 等。只买真正喜欢、有设计感的，不逛完整个商场。目标21:35左右结束，给买水果留时间。','Leave the restaurant around 19:20–19:30 after dinner (the map shows the route from the selected restaurant). Tonight only covers what Koh Larn needs on the 27th: start with GENTLEWOMAN for swimwear and cover-ups, then dresses, shorts, camisoles and other womenswear; check Rip Curl and others if no swimwear fits. Buy only pieces you genuinely like — no full-mall browsing. Aim to finish around 21:35 and leave time for fruit.','夕食後19:20–19:30頃に店を出発（右の地図は選んだ店からのルートを表示）。26日は27日のラン島に必要な買い物だけ。まずGENTLEWOMANで水着・カバーアップ、その後ワンピース・ショートパンツ・キャミなどをチェックし、水着が無ければRip Curlなども見る。気に入った物だけ買い、全館は回らない。21:35頃に終えてフルーツ購入時間を確保。','ออกจากร้านราว 19:20–19:30 หลังมื้อเย็น (แผนที่แสดงเส้นทางจากร้านที่เลือก) คืนนี้ซื้อเฉพาะของที่ต้องใช้ที่เกาะล้านวันที่ 27: เริ่มจาก GENTLEWOMAN ดูชุดว่ายน้ำ/ชุดคลุม แล้วดูเดรส กางเกงขาสั้น สายเดี่ยว ฯลฯ ถ้าไม่เจอชุดว่ายน้ำค่อยดู Rip Curl ซื้อเฉพาะที่ชอบจริง ไม่เดินทั้งห้าง เป้าหมายเสร็จราว 21:35 เผื่อเวลาซื้อผลไม้'),map:'https://www.google.com/maps/dir/?api=1&origin='+GC_Q+'&destination=Terminal+21+Pattaya&travelmode=driving',web:'https://www.terminal21.co.th/pattaya/',est:T4('购物自定','Shopping — up to you','買い物は自由枠','ช้อปปิ้งตามใจ'),actual:false,routeFromAltOf:'d26_5',routeDest:'Terminal 21 Pattaya',routeMode:'driving'},
{id:'d26_6',day:26,time:'21:35–21:55',title:T4('Terminal 21｜顺路买水果','Terminal 21 | buy fruit before leaving','Terminal 21｜帰る前にフルーツ購入','Terminal 21 | ซื้อผลไม้ก่อนกลับ'),desc:T4('购物结束后直接在商场里的超市/食品区买水果，不再专程去 New Naklua Market。按当天品质挑芒果、山竹、红毛丹、龙眼、椰子等，带回酒店晚上吃或第二天早上吃。','After shopping, buy fruit directly in the mall supermarket/food area instead of making a separate trip to New Naklua Market. Choose mango, mangosteen, rambutan, longan, coconut or other fruit based on freshness and take it back to the hotel.','買い物後はNew Naklua Marketへ別移動せず、モール内のスーパー／食品エリアでフルーツを購入。マンゴー、マンゴスチン、ランブータン、ロンガン、ココナッツなどを当日の状態で選びホテルへ持ち帰る。','หลังช้อปให้ซื้อผลไม้ในซูเปอร์มาร์เก็ต/โซนอาหารของห้างเลย ไม่ต้องไป New Naklua Market เพิ่ม เลือกมะม่วง มังคุด เงาะ ลำไย มะพร้าว ฯลฯ ตามความสด แล้วนำกลับโรงแรม'),map:'https://www.google.com/maps/search/?api=1&query=Terminal+21+Pattaya',web:'https://www.terminal21.co.th/pattaya/',est:'฿150–400 / ¥720–1,920'},
{id:'d26_7',day:26,time:'22:00+',title:T4('回 Garden Cliff｜水果 + 休息','Return to Garden Cliff | fruit & rest','Garden Cliffへ戻る｜フルーツ・休憩','กลับ Garden Cliff | กินผลไม้และพักผ่อน'),desc:T4('买完水果直接回酒店（可先确认酒店 Shuttle 是否有末班，否则叫车约10分钟）。回房间吃水果、洗澡休息，为27号格兰岛留体力。','Head straight back to the hotel after buying fruit (check whether a late hotel shuttle runs; otherwise a car takes about 10 minutes). Have fruit, shower and rest for Koh Larn the next day.','フルーツ購入後はホテルへ直帰（シャトルの最終便を確認し、無ければ車で約10分）。部屋でフルーツ・シャワー・休憩し、翌日のラン島に備える。','ซื้อผลไม้แล้วกลับโรงแรมทันที (เช็กรอบสุดท้ายของรถรับส่งโรงแรม ไม่มีก็เรียกรถราว 10 นาที) กลับห้องกินผลไม้ อาบน้ำ พักผ่อนเพื่อเกาะล้านวันถัดไป'),map:'https://www.google.com/maps/dir/?api=1&origin=Terminal+21+Pattaya&destination='+GC_Q+'&travelmode=driving',web:'https://gardencliffpattaya.com/',est:T4('交通按实际','Transport as incurred','交通費は実費','ค่าเดินทางตามจริง')},
{id:'d26_massage',day:26,time:'弹性 / Flex',optional:true,title:T4('可选｜Nil Spa 按摩 60分钟（有时间才做）','Optional | Nil Spa 60-min massage (only if time allows)','任意｜Nil Spa 60分マッサージ（時間があれば）','ตัวเลือก | นวด Nil Spa 60 นาที (ถ้ามีเวลา)'),desc:T4('纯备选，不占固定时段，也不为了按摩赶时间。只有当天意外提前到酒店、主计划还有充足余量，或从 Terminal 21 回来后 Nil Spa 仍营业且两个人都不累时才考虑。入住时顺便向前台确认营业时间和是否需要预约；任何情况下都优先执行 Bamboo Beach → Terminal 21 → 买水果 → 回酒店休息。','Purely optional with no fixed slot, and never worth rushing the schedule for. Consider it only if you unexpectedly reach the hotel early with plenty of buffer, or after returning from Terminal 21 if Nil Spa is still open and both of you still have energy. Ask reception about hours and booking at check-in. The Bamboo Beach → Terminal 21 → fruit → hotel flow always comes first.','固定時間を持たない完全な任意項目で、マッサージのために急がない。ホテルへ予定よりかなり早く着いて主計画に十分な余裕がある場合、またはTerminal 21から戻った後もNil Spaが営業中で2人とも疲れていない場合だけ検討。チェックイン時に営業時間と予約要否を確認し、Bamboo Beach → Terminal 21 → フルーツ → ホテル休憩の主計画を常に優先する。','เป็นตัวเลือกเสริมล้วน ๆ ไม่มีเวลาบังคับ และไม่ต้องรีบเพื่อนวด พิจารณาเฉพาะเมื่อถึงโรงแรมเร็วกว่ากำหนดมากและยังมีเวลาเหลือ หรือหลังกลับจาก Terminal 21 แล้ว Nil Spa ยังเปิดและทั้งสองคนยังไม่เหนื่อย ตอนเช็กอินให้ถามเวลาเปิดและต้องจองไหม โดยให้แผน Bamboo Beach → Terminal 21 → ซื้อผลไม้ → กลับโรงแรมมาก่อนเสมอ'),map:'https://www.google.com/maps/search/?api=1&query='+GC_Q,web:'https://gardencliffpattaya.com/facilities.html',est:'฿1,000–1,800 / ¥4,800–8,600'}
];