const plans26 = [
{id:"d26_f1",day:26,time:"08:15–11:45",
  title:{zh:"FD237｜FUK → DMK",en:"FD237 | FUK → DMK",ja:"FD237｜FUK → DMK",th:"FD237 | FUK → DMK"},
  desc:{zh:"你的去程航班：福冈 08:15 起飞，11:45 抵达曼谷廊曼机场。机票金额为往返合计。",en:"Your outbound flight: depart Fukuoka at 08:15 and arrive at Bangkok Don Mueang at 11:45. The amount shown is the round-trip fare.",ja:"あなたの往路便：福岡08:15発、バンコク・ドンムアン11:45着。表示金額は往復航空券の合計。",th:"เที่ยวบินขาไปของคุณ: ออกจากฟุกุโอกะ 08:15 ถึงดอนเมือง 11:45 ยอดที่แสดงเป็นค่าโดยสารไป-กลับ"},
  map:"https://www.google.com/maps/search/?api=1&query=Fukuoka+Airport",
  web:"https://www.airasia.com/", est:{zh:"往返机票｜¥60,000 / 人",en:"Round trip｜¥60,000 / person",ja:"往復航空券｜¥60,000 / 人",th:"ไป-กลับ｜¥60,000 / คน"}, actual:false},
{id:"d26_f2",day:26,time:"09:15–14:00",
  title:{zh:"森田航班｜NRT → DMK",en:"Morita's flight | NRT → DMK",ja:"森田の便｜NRT → DMK",th:"เที่ยวบิน Morita | NRT → DMK"},
  desc:{zh:"森田从东京成田出发，09:15 起飞、14:00 抵达 DMK。航班号待确认。机票金额为往返合计。",en:"Morita departs Tokyo Narita at 09:15 and arrives at DMK at 14:00. Flight number to be confirmed. The amount shown is the round-trip fare.",ja:"森田は成田09:15発、DMK14:00着。便名は確認待ち。表示金額は往復航空券の合計。",th:"Morita ออกจากนาริตะ 09:15 ถึง DMK 14:00 หมายเลขเที่ยวบินรอยืนยัน ยอดที่แสดงเป็นค่าโดยสารไป-กลับ"},
  map:"https://www.google.com/maps/search/?api=1&query=Narita+International+Airport",
  web:"https://www.airasia.com/", est:{zh:"往返机票｜¥60,000 / 人",en:"Round trip｜¥60,000 / person",ja:"往復航空券｜¥60,000 / 人",th:"ไป-กลับ｜¥60,000 / คน"}, actual:false},
{id:"d26_1",day:26,time:"11:45–14:00",
  title:{zh:"抵达 DMK｜入境、取行李、等森田",en:"Arrive at DMK | immigration, bags and wait",ja:"DMK到着｜入国・荷物受取・森田待ち",th:"ถึง DMK | ตม. รับกระเป๋า และรอ Morita"},
  desc:{zh:"FD237抵达后完成入境和取行李，在机场休息并等森田14:00抵达。",en:"After FD237 arrives, clear immigration, collect luggage and wait at the airport for Morita arriving at 14:00.",ja:"FD237到着後、入国審査と荷物受取を済ませ、14:00着の森田を空港で待つ。",th:"หลัง FD237 ถึง ผ่าน ตม. รับกระเป๋า และรอ Morita ที่จะถึงเวลา 14:00"},
  map:"https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport",
  web:"https://donmueang.airportthai.co.th/", est:"฿0 / ¥0", actual:false},
{id:"d26_2",day:26,time:"14:00–15:00",
  title:{zh:"森田抵达 DMK → 汇合",en:"Morita arrives at DMK → meet up",ja:"森田がDMK到着 → 合流",th:"Morita ถึง DMK → พบกัน"},
  desc:{zh:"森田完成入境、取行李后汇合。按约15:00–15:30从机场出发。",en:"Meet after Morita clears immigration and collects luggage. Plan to leave the airport around 15:00–15:30.",ja:"森田の入国審査・荷物受取後に合流し、15:00–15:30頃に空港を出発。",th:"พบกันหลัง Morita ผ่าน ตม. และรับกระเป๋า วางแผนออกจากสนามบินประมาณ 15:00–15:30"},
  map:"https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport",
  web:"https://donmueang.airportthai.co.th/", est:"฿0 / ¥0", actual:false},
{id:"d26_3",day:26,time:"15:00–15:30",
  title:{zh:"DMK → Garden Cliff",en:"DMK → Garden Cliff",ja:"DMK → Garden Cliff",th:"DMK → Garden Cliff"},
  desc:{zh:"两人一起乘预约车前往芭提雅酒店。",en:"Take a pre-booked car together to the Pattaya hotel.",ja:"予約車で一緒にパタヤのホテルへ移動。",th:"เดินทางด้วยรถที่จองไว้ไปโรงแรมที่พัทยา"},
  map:"https://www.google.com/maps/dir/?api=1&origin=Don+Mueang+International+Airport&destination=Garden+Cliff+Resort+%26+Spa+Pattaya",
  web:"https://www.pattaya-transfer.com/dmk-to-pattaya-price.aspx", est:"฿1,499 / ¥7,200"},
{id:"d26_4",day:26,time:"17:30–18:00",
  title:{zh:"入住 Garden Cliff｜2晚",en:"Check in at Garden Cliff | 2 nights",ja:"Garden Cliffチェックイン｜2泊",th:"เช็กอิน Garden Cliff | 2 คืน"},
  desc:{zh:"办理入住、洗澡、休息，有精神就去酒店海边走走。酒店已订，8月26–27日两晚，两人合计 ¥21,000。",en:"Check in, shower and rest; walk by the hotel beach if you feel like it. Booked for Aug 26–27, two nights for two people, ¥21,000 total.",ja:"チェックイン、シャワー、休憩。余裕があればホテルの海辺を散歩。8月26–27日の2泊、2人合計¥21,000で予約済み。",th:"เช็กอิน อาบน้ำ พักผ่อน และเดินเล่นริมทะเลถ้ายังมีแรง จองวันที่ 26–27 ส.ค. 2 คืน 2 คน รวม ¥21,000"},
  map:"https://www.google.com/maps/search/?api=1&query=Garden+Cliff+Resort+%26+Spa+Pattaya",
  web:"https://gardencliffpattaya.com/", est:{zh:"已订｜2晚·2人 ¥21,000",en:"Booked｜2 nights · 2 people ¥21,000",ja:"予約済み｜2泊·2人 ¥21,000",th:"จองแล้ว｜2 คืน · 2 คน ¥21,000"}, actual:false},
{id:"d26_5",day:26,time:"19:30",
  title:{zh:"Bamboo Beach 海边晚餐",en:"Dinner at Bamboo Beach",ja:"Bamboo Beachで海辺の夕食",th:"อาหารเย็นที่ Bamboo Beach"},
  desc:{zh:"泰国菜、海鲜为主；冬阴功、Som Tam、Pad Thai、烤虾/烤鱿鱼等。",en:"Thai food and seafood: tom yum, som tam, pad thai, grilled shrimp or squid.",ja:"タイ料理とシーフード。トムヤム、ソムタム、パッタイ、エビやイカのグリルなど。",th:"อาหารไทยและซีฟู้ด เช่น ต้มยำ ส้มตำ ผัดไทย กุ้งหรือปลาหมึกย่าง"},
  map:"https://www.google.com/maps/search/?api=1&query=Bamboo+Beach+Pattaya",
  web:"https://www.facebook.com/BambooBeachPattaya/", est:"฿400–1,000 / ¥1,900–4,800"},
{id:"d26_6",day:26,time:"20:45–21:15",
  title:{zh:"New Naklua Market 买水果",en:"Buy fruit at New Naklua Market",ja:"New Naklua Marketでフルーツ購入",th:"ซื้อผลไม้ที่ New Naklua Market"},
  desc:{zh:"山竹、红毛丹、龙眼、芒果、椰子等按当天品质购买。",en:"Choose mangosteen, rambutan, longan, mango, coconut and other fruit by quality.",ja:"マンゴスチン、ランブータン、ロンガン、マンゴー、ココナッツなどを当日の状態で選ぶ。",th:"เลือกมังคุด เงาะ ลำไย มะม่วง มะพร้าว และผลไม้อื่นตามคุณภาพวันนั้น"},
  map:"https://www.google.com/maps/search/?api=1&query=New+Naklua+Market+Pattaya+City",
  web:"https://pattayapointer.com/activities/new-naklua-market-pattaya-city/", est:"฿150–400 / ¥720–1,920"},
{id:"d26_7",day:26,time:"21:30+",
  title:{zh:"回 Garden Cliff 休息",en:"Return to Garden Cliff",ja:"Garden Cliffへ戻って休憩",th:"กลับ Garden Cliff พักผ่อน"},
  desc:{zh:"早点休息，为27号格兰岛留体力。",en:"Rest early for Koh Larn the next day.",ja:"翌日のラン島に備えて早めに休む。",th:"พักผ่อนให้เพียงพอสำหรับเกาะล้านวันถัดไป"},
  map:"https://www.google.com/maps/search/?api=1&query=Garden+Cliff+Resort+%26+Spa+Pattaya",
  web:"https://gardencliffpattaya.com/", est:"฿100–250 / ¥480–1,200"}
];
