const plans29=[
{id:'29a',day:29,time:'09:40–10:30',title:L('起床、整理、退房','Wake up, pack & check out','起床・荷造り・チェックアウト','ตื่นนอน จัดกระเป๋า และเช็กเอาต์'),desc:L('按今天实际节奏压缩上午行程。','Morning itinerary compressed to match today’s actual timing.','今日の実際の時間に合わせて午前予定を短縮。','ปรับช่วงเช้าให้กระชับตามเวลาจริงวันนี้'),map:'https://www.google.com/maps/search/?api=1&query=FuramaXclusive+Asoke+Bangkok',web:'https://www.furama.com/furamaxclusive/asoke/',est:'฿0 / ¥0',actual:true},

{id:'29b',day:29,time:'10:30',title:L('AIRPORTELs 行李寄送｜已完成','AIRPORTELs luggage delivery | completed','AIRPORTELs 荷物配送｜完了','AIRPORTELs ส่งกระเป๋า | เสร็จแล้ว'),desc:L('两个背包已从 FuramaXclusive Asoke 寄往 DMK。总价 ฿598，20:05 可在 DMK 取件；今天不再返回酒店。','Two backpacks have been sent from FuramaXclusive Asoke to DMK. Total ฿598; available for pickup at DMK at 20:05. No return to the hotel is needed.','バックパック2個をFuramaXclusive AsokeからDMKへ配送済み。合計฿598、20:05にDMKで受取可能。ホテルへ戻る必要なし。','ส่งกระเป๋าเป้ 2 ใบจาก FuramaXclusive Asoke ไป DMK แล้ว รวม ฿598 รับได้ที่ DMK เวลา 20:05 ไม่ต้องกลับโรงแรม'),map:'https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport+Terminal+2+Gate+9',web:'https://www.airportels.asia/',est:'฿598 / ¥2,870',actual:true},

{id:'29c3',day:29,time:'行李寄出后',title:L('午饭｜Terminal 21 船面｜已完成','Lunch | boat noodles at Terminal 21 | completed','昼食｜Terminal 21のボートヌードル｜完了','มื้อกลางวัน | ก๋วยเตี๋ยวเรือที่ Terminal 21 | เสร็จแล้ว'),desc:L('AIRPORTELs 行李寄出后已在 Terminal 21 吃过船面。Wat Arun 一带不再安排午饭，抵达 Bestie 后直接化妆、做发型和换泰服。','After sending the luggage with AIRPORTELs, lunch was already finished at Terminal 21 with boat noodles. No lunch stop is needed near Wat Arun; go straight into makeup, hair and costume at Bestie.','AIRPORTELsで荷物を送った後、Terminal 21でボートヌードルの昼食を済ませた。Wat Arun周辺では昼食を入れず、Bestie到着後すぐメイク・ヘア・衣装へ。','หลังส่งกระเป๋ากับ AIRPORTELs กินก๋วยเตี๋ยวเรือที่ Terminal 21 เรียบร้อยแล้ว ไม่ต้องแวะกินใกล้ Wat Arun ไป Bestie แล้วเริ่มแต่งหน้า ทำผม และเปลี่ยนชุดได้เลย'),map:'https://www.google.com/maps/search/?api=1&query=Terminal+21+Asok+Bangkok',web:'https://www.terminal21.co.th/asok/',est:L('已吃｜金额未记录','Completed | amount not recorded','食事済み｜金額未記録','กินแล้ว | ยังไม่ได้บันทึกราคา'),actual:true},

{id:'29c',day:29,time:'11:35–12:20左右',title:L('Terminal 21 → Bestie Thai Costume','Terminal 21 → Bestie Thai Costume','Terminal 21 → Bestie Thai Costume','Terminal 21 → Bestie Thai Costume'),desc:L('今天推荐 Grab/Bolt：约25–45分钟，约฿180–300/车，从 Terminal 21/Asoke 直接到 Bestie，最省体力。轨道方案：MRT Sukhumvit → Sanam Chai → 步行到 Tha Tien → 横渡船到 Wat Arun，再走到 Bestie；约50–65分钟，约฿45–55/人，价格低且不怕堵车，但换乘和步行较多。当前优先 Grab/Bolt。','Recommended today: Grab/Bolt, about 25–45 min and roughly ฿180–300/car, direct from Terminal 21/Asoke to Bestie and easiest. Rail option: MRT Sukhumvit → Sanam Chai → walk to Tha Tien → cross-river ferry → Bestie; about 50–65 min, roughly ฿45–55/person, cheaper and traffic-proof but with more walking/transfers. Grab/Bolt is preferred now.','今日はGrab/Bolt推奨：約25〜45分、฿180〜300/台。Terminal 21/AsokeからBestieへ直行でき最も楽。鉄道案はMRT Sukhumvit → Sanam Chai → Tha Tienまで徒歩 → 渡し船 → Bestie。約50〜65分、฿45〜55/人。安く渋滞に強いが歩行・乗換が多い。','วันนี้แนะนำ Grab/Bolt ประมาณ 25–45 นาที ราว ฿180–300/คัน จาก Terminal 21/Asoke ตรงไป Bestie สะดวกที่สุด ทางเลือก MRT: Sukhumvit → Sanam Chai → เดินไป Tha Tien → เรือข้ามฟาก → Bestie ใช้ประมาณ 50–65 นาที ราว ฿45–55/คน ถูกกว่าและไม่ติดรถ แต่เดินและเปลี่ยนหลายครั้ง'),map:'https://www.google.com/maps/dir/?api=1&origin=Terminal+21+Asok+Bangkok&destination=Bestie+Thai+Costume+199+Thanon+Wang+Doem+Bangkok&travelmode=driving',web:'https://bestiethaicostume.com/directions/',est:L('推荐 Grab/Bolt｜฿180–300/车；MRT+船｜฿45–55/人','Grab/Bolt preferred | ฿180–300/car; MRT+ferry | ฿45–55/person','Grab/Bolt推奨｜฿180–300/台；MRT+船｜฿45–55/人','แนะนำ Grab/Bolt | ฿180–300/คัน; MRT+เรือ | ฿45–55/คน')},

{id:'29d',day:29,time:'12:20–13:20',title:L('Bestie｜化妆 + 发型 + 换泰服','Bestie | makeup + hair + Thai costume','Bestie｜メイク + ヘア + タイ衣装','Bestie | แต่งหน้า + ทำผม + ชุดไทย'),desc:L('已确定 Bestie Thai Costume，199 Thanon Wang Doem。女装参考：Standard ฿300、Premium ฿600；化妆 ฿300、发型 ฿100，现场按衣服和排队情况决定。已经吃过午饭，到店可直接开始。','Bestie Thai Costume is selected, at 199 Thanon Wang Doem. Ladies’ reference prices: Standard ฿300, Premium ฿600; makeup ฿300 and hair ฿100. Lunch is already done, so start as soon as the shop is ready.','Bestie Thai Costume（199 Thanon Wang Doem）に決定。女性参考料金：Standard ฿300、Premium ฿600、メイク฿300、ヘア฿100。昼食済みなので、到着後すぐ開始可能。','เลือกร้าน Bestie Thai Costume ที่ 199 Thanon Wang Doem ราคาอ้างอิงชุดผู้หญิง Standard ฿300, Premium ฿600, แต่งหน้า ฿300, ทำผม ฿100 กินมื้อกลางวันแล้วจึงเริ่มได้ทันทีเมื่อร้านพร้อม'),map:'https://www.google.com/maps/search/?api=1&query=Bestie+Thai+Costume+199+Thanon+Wang+Doem+Bangkok',web:'https://bestiethaicostume.com/price-list/',est:L('按现场选择','Choose on site','店頭で選択','เลือกที่ร้าน')},

{id:'29e',day:29,time:'13:20–14:40',title:L('Wat Arun 郑王庙｜泰服拍照','Wat Arun in Thai costume','タイ衣装でワット・アルン','วัดอรุณในชุดไทย'),desc:L('换好泰服后直接进 Wat Arun 拍照和参观。今天优先保证这一项。','Go straight into Wat Arun for photos and sightseeing after changing. This is the priority activity today.','着替え後そのままWat Arunで撮影・見学。今日はこの予定を最優先。','เปลี่ยนชุดแล้วเข้า Wat Arun เพื่อถ่ายรูปและเที่ยวชม กิจกรรมนี้เป็นลำดับสำคัญของวันนี้'),map:'https://www.google.com/maps/search/?api=1&query=Wat+Arun+Ratchawararam+Bangkok',web:'https://www.thailandtravel.or.jp/wat-arun/',est:'฿200 / ¥960'},

{id:'29f',day:29,time:'14:40–15:05',title:L('还泰服 → Wat Pho｜横渡船','Return costume → Wat Pho | ferry','衣装返却 → Wat Pho｜渡し船','คืนชุด → Wat Pho | เรือข้ามฟาก'),desc:L('推荐横渡船：回 Bestie 还衣服后步行到 Wat Arun Pier → Tha Tien Pier，船程几分钟，约฿5–10/人，最快也最有体验感。Grab/Bolt 需要绕桥，通常约20–40分钟、约฿100–180/车，没有必要。','Recommended: return the costume, walk to Wat Arun Pier and take the cross-river ferry to Tha Tien. Only a few minutes on the boat, roughly ฿5–10/person, fastest and simplest. Grab/Bolt must detour via a bridge, usually about 20–40 min and ฿100–180/car, so it is unnecessary.','衣装返却後、Wat Arun PierからTha Tien Pierへの渡し船推奨。船は数分、約฿5〜10/人で最速。Grab/Boltは橋へ迂回するため約20〜40分、฿100〜180/台で非効率。','แนะนำเรือข้ามฟาก หลังคืนชุดเดินไป Wat Arun Pier → Tha Tien ใช้เวลาไม่กี่นาที ราว ฿5–10/คน เร็วที่สุด Grab/Bolt ต้องอ้อมสะพาน มักใช้ 20–40 นาที ราว ฿100–180/คัน ไม่คุ้ม'),map:'https://www.google.com/maps/dir/?api=1&origin=Wat+Arun+Pier+Bangkok&destination=Tha+Tien+Pier+Bangkok&travelmode=walking',web:'https://thailandboat.com/bangkok/ferry-tha-tien-pier-wat-arun',est:L('推荐渡船｜฿5–10/人；Grab｜฿100–180/车','Ferry preferred | ฿5–10/person; Grab | ฿100–180/car','渡し船推奨｜฿5–10/人；Grab｜฿100–180/台','แนะนำเรือ | ฿5–10/คน; Grab | ฿100–180/คัน')},

{id:'29g',day:29,time:'15:05–15:50',title:L('Wat Pho 卧佛寺｜机动项','Wat Pho | flexible stop','Wat Pho｜調整可能','Wat Pho | ปรับได้'),desc:L('控制在约45分钟。若 Bestie 排队、化妆或 Wat Arun 拍照延误，优先取消 Wat Pho，直接去 Chatuchak，以保证周六市场时间。','Keep this to about 45 minutes. If Bestie, makeup or Wat Arun photos run late, skip Wat Pho and go directly to Chatuchak to protect Saturday market time.','約45分に限定。Bestieの待ち時間、メイク、Wat Arun撮影が遅れた場合はWat Phoを省略し、Chatuchakへ直行して週末市場の時間を確保。','ใช้เวลาประมาณ 45 นาที หากคิว Bestie แต่งหน้า หรือถ่ายรูป Wat Arun ล่าช้า ให้ตัด Wat Pho และไป Chatuchak โดยตรงเพื่อรักษาเวลาตลาดวันเสาร์'),map:'https://www.google.com/maps/search/?api=1&query=Wat+Phra+Chetuphon+Wimon+Mangkhalaram+2+Sanam+Chai+Road+Bangkok',web:'https://www.watpho.com/en/contact/plan',est:'฿300 / ¥1,440',optional:true},

{id:'29h',day:29,time:'15:50–16:35',title:L('Wat Pho → Chatuchak｜MRT优先','Wat Pho → Chatuchak | MRT preferred','Wat Pho → Chatuchak｜MRT推奨','Wat Pho → Chatuchak | แนะนำ MRT'),desc:L('推荐 MRT：Wat Pho 步行约5–10分钟到 Sanam Chai，Blue Line 直达 Kamphaeng Phet；总计约40–50分钟，约฿40–45/人，稳定、不受堵车影响，出口就是 Chatuchak。Grab/Bolt：约30–60+分钟，约฿180–300/车，少走路但下午堵车风险高。今天优先 MRT。','Recommended: walk about 5–10 min from Wat Pho to MRT Sanam Chai and take the Blue Line directly to Kamphaeng Phet. Total about 40–50 min, roughly ฿40–45/person, reliable and traffic-proof, with the exit at Chatuchak. Grab/Bolt: about 30–60+ min, roughly ฿180–300/car; less walking but high afternoon traffic risk. MRT is preferred today.','Wat PhoからSanam Chaiまで徒歩5〜10分、Blue LineでKamphaeng Phetへ直行するMRT推奨。合計約40〜50分、฿40〜45/人、渋滞なし。Grab/Boltは約30〜60分以上、฿180〜300/台で午後の渋滞リスクあり。今日はMRT優先。','แนะนำ MRT เดินจาก Wat Pho ไป Sanam Chai ประมาณ 5–10 นาที แล้วนั่ง Blue Line ตรงไป Kamphaeng Phet รวมประมาณ 40–50 นาที ราว ฿40–45/คน ไม่ติดรถและออกถึง Chatuchak ส่วน Grab/Bolt ประมาณ 30–60+ นาที ราว ฿180–300/คัน เสี่ยงรถติดช่วงบ่าย วันนี้เลือก MRT'),map:'https://www.google.com/maps/dir/?api=1&origin=Wat+Pho+Bangkok&destination=Chatuchak+Weekend+Market+Bangkok&travelmode=transit',web:'https://metro.bemplc.co.th/',est:L('推荐 MRT｜฿40–45/人；Grab｜฿180–300/车','MRT preferred | ฿40–45/person; Grab | ฿180–300/car','MRT推奨｜฿40–45/人；Grab｜฿180–300/台','แนะนำ MRT | ฿40–45/คน; Grab | ฿180–300/คัน')},

{id:'29i',day:29,time:'16:35–18:00',title:L('Chatuchak Weekend Market｜周六市场','Chatuchak Weekend Market | Saturday','Chatuchak Weekend Market｜土曜','Chatuchak Weekend Market | วันเสาร์'),desc:L('重点逛服饰、纪念品、小物和零食。主市场约18:00开始收摊，今天不拖延。若取消 Wat Pho，可更早到并增加市场时间。','Focus on clothes, souvenirs, small goods and snacks. The main market starts winding down around 18:00, so do not linger elsewhere. If Wat Pho is skipped, arrive earlier and gain more market time.','服、土産、小物、軽食を中心に。メイン市場は18:00頃から閉まり始めるため延長しない。Wat Phoを省略すれば早く到着できる。','เน้นเสื้อผ้า ของฝาก ของจุกจิก และของกิน ตลาดหลักเริ่มปิดราว 18:00 จึงไม่ควรช้า หากตัด Wat Pho จะมีเวลาในตลาดมากขึ้น'),map:'https://www.google.com/maps/search/?api=1&query=587%2F10+Kamphaeng+Phet+2+Rd+Chatuchak+Bangkok+10900',web:'https://www.chatuchakmarket.org/',est:'฿300–1,500 / ¥1,440–7,200'},

{id:'29j',day:29,time:'18:00–19:00左右',title:L('Chatuchak → DMK｜轨道或Grab二选一','Chatuchak → DMK | rail or Grab','Chatuchak → DMK｜鉄道 / Grab','Chatuchak → DMK | รถไฟหรือ Grab'),desc:L('省钱且避堵：MRT Kamphaeng Phet → Bang Sue，步行连接 Krung Thep Aphiwat，再乘 SRT Dark Red Line → Don Mueang；总计约45–60分钟，约฿50–65/人，换乘一次但时间稳定。最省事：Grab/Bolt 约25–45分钟，约฿180–300/车，直接到航站楼；如果累、下雨或买了很多东西就选 Grab。行李已经在机场，所以两种都方便。','Cheaper and traffic-proof: MRT Kamphaeng Phet → Bang Sue, walk to Krung Thep Aphiwat, then SRT Dark Red Line → Don Mueang; about 45–60 min total, roughly ฿50–65/person, one transfer but reliable. Easiest: Grab/Bolt about 25–45 min, roughly ฿180–300/car, direct to the terminal. Choose Grab if tired, raining or carrying lots of shopping. Luggage is already at the airport, so either works well.','安く渋滞回避：MRT Kamphaeng Phet → Bang Sue、Krung Thep Aphiwatへ徒歩連絡、SRT Dark Red LineでDon Mueang。合計約45〜60分、฿50〜65/人、乗換1回で安定。最も楽なのはGrab/Boltで約25〜45分、฿180〜300/台、空港直行。疲れている・雨・買い物が多い場合はGrab。荷物はすでに空港なのでどちらも使いやすい。','ประหยัดและไม่ติดรถ: MRT Kamphaeng Phet → Bang Sue เดินเชื่อม Krung Thep Aphiwat แล้วนั่ง SRT Dark Red Line → Don Mueang รวมประมาณ 45–60 นาที ราว ฿50–65/คน เปลี่ยน 1 ครั้งแต่เวลาแน่นอน ทางที่ง่ายที่สุดคือ Grab/Bolt ประมาณ 25–45 นาที ราว ฿180–300/คัน ตรงถึงเทอร์มินัล หากเหนื่อย ฝนตก หรือซื้อของเยอะให้เลือก Grab กระเป๋าอยู่สนามบินแล้วจึงสะดวกทั้งสองแบบ'),map:'https://www.google.com/maps/dir/?api=1&origin=Chatuchak+Weekend+Market+Bangkok&destination=Don+Mueang+International+Airport&travelmode=transit',web:'https://www.srtet.co.th/en',est:L('轨道｜฿50–65/人；Grab｜฿180–300/车','Rail | ฿50–65/person; Grab | ฿180–300/car','鉄道｜฿50–65/人；Grab｜฿180–300/台','รถไฟ | ฿50–65/คน; Grab | ฿180–300/คัน')},

{id:'29j1',day:29,time:'19:00–20:05',title:L('DMK｜休息 + 等行李','DMK | rest + wait for luggage','DMK｜休憩 + 荷物待ち','DMK | พัก + รอกระเป๋า'),desc:L('午饭已经吃过，到机场后可先休息、补水或简单加餐。AIRPORTELs 订单显示两个背包 20:05 可取。','Lunch is already done. At the airport, rest, hydrate or have a light snack while waiting. The AIRPORTELs booking shows both backpacks available at 20:05.','昼食済み。空港では休憩、水分補給、軽食程度で待機。AIRPORTELs予約ではバックパック2個は20:05受取可能。','กินมื้อกลางวันแล้ว ที่สนามบินพัก ดื่มน้ำ หรือกินของว่างระหว่างรอ ตามการจอง AIRPORTELs กระเป๋าเป้ 2 ใบรับได้เวลา 20:05'),map:'https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport+Terminal+2+Gate+9',web:'https://www.airportels.asia/',est:'฿0–300 / ¥0–1,440'},

{id:'29j2',day:29,time:'20:05',title:L('DMK｜取 AIRPORTELs 行李','DMK | collect AIRPORTELs luggage','DMK｜AIRPORTELs荷物受取','DMK | รับกระเป๋า AIRPORTELs'),desc:L('按订单在 DMK 取两个背包。取到后办理国际航班值机、安检和出境手续。','Collect both backpacks at DMK according to the booking, then proceed with international check-in, security and immigration.','予約に従いDMKでバックパック2個を受取。その後、国際線チェックイン・保安検査・出国審査へ。','รับกระเป๋าเป้ 2 ใบที่ DMK ตามการจอง แล้วเช็กอินเที่ยวบินระหว่างประเทศ ผ่านจุดตรวจและ ตม.'),map:'https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport+Terminal+2+Gate+9',web:'https://www.airportels.asia/',est:'฿0 / ¥0',actual:false},

{id:'29k',day:29,time:'23:45–次日07:05',title:L('FD236｜两人共同回程 DMK → FUK','FD236 | Return together DMK → FUK','FD236｜2人で帰国 DMK → FUK','FD236 | เดินทางกลับด้วยกัน DMK → FUK'),desc:L('8月29日23:45从DMK起飞，8月30日07:05抵达福冈。','Depart DMK at 23:45 on Aug 29 and arrive in Fukuoka at 07:05 on Aug 30.','8月29日23:45にDMKを出発し、8月30日07:05に福岡到着。','ออกจาก DMK 23:45 วันที่ 29 ส.ค. ถึงฟุกุโอกะ 07:05 วันที่ 30 ส.ค.'),map:'https://www.google.com/maps/search/?api=1&query=Don+Mueang+International+Airport+Terminal+1',web:'https://www.airasia.com/',est:'฿0 / ¥0',actual:false}
];
const plans=[...plans26,...plans27,...plans28,...plans29];