(function(){
  const people={
    ma:{zh:'马',en:'Ma',ja:'馬',th:'Ma'},
    morita:{zh:'森田',en:'Morita',ja:'森田',th:'Morita'}
  };
  const extra={
    zh:{sub:'两个人分别准备。勾选、新增和删除都会先保存在本机；联网时同步到共享行程。',mine:'个人清单'},
    en:{sub:'Separate packing lists for both travelers. Changes save locally first and sync when online.',mine:'Personal list'},
    ja:{sub:'2人分を別々に準備します。変更はまず端末に保存され、オンライン時に共有同期されます。',mine:'個人リスト'},
    th:{sub:'แยกรายการของแต่ละคน บันทึกในเครื่องก่อนและซิงก์เมื่อออนไลน์',mine:'รายการส่วนตัว'}
  };
  const langNow=()=>typeof lang!=='undefined'?lang:'zh';
  const key=(person,type)=>`tripPrep:${person}:${type}`;
  const read=(person,type,def)=>{try{return JSON.parse(localStorage.getItem(key(person,type))||JSON.stringify(def))}catch(e){return def}};
  const write=(person,type,v)=>localStorage.setItem(key(person,type),JSON.stringify(v));
  const activePerson=()=>localStorage.getItem('tripPrepActivePerson')||'ma';
  function migrate(){if(localStorage.getItem(key('ma','migrated')))return;const legacy=[['ready','tripPrepReady',{}],['custom','tripPrepCustom',[]],['deleted','tripPrepDeleted',[]]];legacy.forEach(([type,k,d])=>{if(localStorage.getItem(key('ma',type))==null){try{const v=JSON.parse(localStorage.getItem(k)||JSON.stringify(d));write('ma',type,v)}catch(e){write('ma',type,d)}}});localStorage.setItem(key('ma','migrated'),'1');}
  function state(p){return read(p,'ready',{})}function custom(p){return read(p,'custom',[])}function deleted(p){return read(p,'deleted',[])}
  function items(p){const del=new Set(deleted(p));return [...prepDefaults.filter(x=>!del.has(x.id)),...custom(p).filter(x=>!del.has(x.id))]}
  function nameOf(x){const l=langNow();return x.custom?x.name:(x.n[l]||x.n.zh)}
  function sync(p,id,data){if(window.TripSync)TripSync.putPrep(p,id,data)}
  function setChecked(p,id,val){const s=state(p);s[id]=val;write(p,'ready',s);const x=items(p).find(x=>x.id===id);sync(p,id,{checked:val,deleted:false,custom_name:x&&x.custom?x.name:null,category:x?x.cat:null});renderPerson(p)}
  function add(p){const inp=document.getElementById('packInput_'+p),cat=document.getElementById('packCat_'+p);if(!inp||!cat)return;const n=inp.value.trim();if(!n)return;const x={id:'custom_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),cat:cat.value,custom:true,name:n};const a=custom(p);a.push(x);write(p,'custom',a);inp.value='';sync(p,x.id,{checked:false,deleted:false,custom_name:n,category:x.cat});renderPerson(p)}
  function remove(p,x){const d=deleted(p);if(!d.includes(x.id))d.push(x.id);write(p,'deleted',d);const s=state(p);delete s[x.id];write(p,'ready',s);sync(p,x.id,{checked:false,deleted:true,custom_name:x.custom?x.name:null,category:x.cat});renderPerson(p)}
  function restore(p){const t=prepLang();if(!confirm(t.confirmRestore))return;write(p,'ready',{});write(p,'custom',[]);write(p,'deleted',[]);prepDefaults.forEach(x=>sync(p,x.id,{checked:false,deleted:false,custom_name:null,category:x.cat}));renderPerson(p)}
  function renderPerson(p){const t=prepLang(),l=langNow(),list=document.getElementById('packList_'+p);if(!list)return;const its=items(p),s=state(p);list.innerHTML='';const grouped={};Object.keys(t.cats).forEach(k=>grouped[k]=[]);its.forEach(x=>(grouped[x.cat]||(grouped[x.cat]=[])).push(x));Object.entries(grouped).forEach(([cat,arr])=>{if(!arr.length)return;const h=document.createElement('div');h.className='pack-category';h.textContent=t.cats[cat]||cat;list.appendChild(h);arr.forEach(x=>{const done=!!s[x.id],row=document.createElement('div');row.className='pack-row'+(done?' done':'');row.innerHTML=`<input class="pack-check" type="checkbox" ${done?'checked':''}><div><div class="pack-name">${esc(nameOf(x))}</div><div class="pack-status">${done?esc(t.ready):esc(t.pending)}</div></div><button class="pack-delete">${esc(t.delete)}</button>`;row.querySelector('.pack-check').onchange=e=>setChecked(p,x.id,e.target.checked);row.querySelector('.pack-delete').onclick=()=>remove(p,x);list.appendChild(row)})});const ready=its.filter(x=>s[x.id]).length,total=its.length,pct=total?Math.round(ready/total*100):0;document.getElementById('packProgress_'+p).textContent=`${t.progress}: ${ready}/${total} · ${pct}%`;document.getElementById('packFill_'+p).style.width=pct+'%';}
  function switchPerson(p,save=true){if(!people[p])p='ma';if(save)localStorage.setItem('tripPrepActivePerson',p);document.querySelectorAll('.dual-person-card').forEach(el=>el.classList.toggle('mobile-active',el.dataset.person===p));document.querySelectorAll('.dual-pack-tab').forEach(btn=>{const on=btn.dataset.person===p;btn.classList.toggle('active',on);btn.setAttribute('aria-selected',on?'true':'false')});}
  function install(){migrate();const content=document.getElementById('prepContent');if(!content)return;const cards=[...content.querySelectorAll(':scope > .prep-card')];if(cards.length<2)return;const old=cards[cards.length-1];const t=prepLang(),l=langNow(),x=extra[l]||extra.zh;old.style.display='none';let wrap=document.getElementById('dualPacking');if(!wrap){wrap=document.createElement('div');wrap.id='dualPacking';old.after(wrap);const st=document.createElement('style');st.id='dualPackingStyle';st.textContent='.dual-pack-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.dual-pack-tabs{display:none}.person-title{display:flex;align-items:center;gap:8px}.person-badge{display:inline-flex;align-items:center;justify-content:center;min-width:34px;height:26px;padding:0 9px;border-radius:999px;background:#173f3a;color:#fff;font-size:12px;font-weight:850}.dual-note{margin:0 0 12px;color:#65746f;font-size:12px;line-height:1.55}@media(max-width:860px){.dual-pack-tabs{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:0 0 12px;padding:4px;background:#edf2f0;border:1px solid #dde6e2;border-radius:12px;position:sticky;top:74px;z-index:8}.dual-pack-tab{border:0;background:transparent;color:#60706b;border-radius:9px;padding:10px 12px;font-size:14px;font-weight:850;cursor:pointer}.dual-pack-tab.active{background:#173f3a;color:#fff;box-shadow:0 2px 6px rgba(23,63,58,.16)}.dual-pack-grid{grid-template-columns:1fr}.dual-person-card{display:none}.dual-person-card.mobile-active{display:block}}';document.head.appendChild(st)}
    wrap.innerHTML=`<p class="dual-note">${esc(x.sub)}</p><div class="dual-pack-tabs" role="tablist" aria-label="Travelers"><button class="dual-pack-tab" data-person="ma" role="tab">${esc(people.ma[l]||people.ma.zh)}</button><button class="dual-pack-tab" data-person="morita" role="tab">${esc(people.morita[l]||people.morita.zh)}</button></div><div class="dual-pack-grid">${['ma','morita'].map(p=>`<div class="prep-card dual-person-card" data-person="${p}"><div class="pack-head"><div class="person-title"><span class="person-badge">${esc(people[p][l]||people[p].zh)}</span><h3 style="margin:0">${esc(t.luggageTitle)}</h3></div><div class="pack-progress" id="packProgress_${p}"></div></div><div class="pack-bar"><div class="pack-fill" id="packFill_${p}"></div></div><div class="pack-add"><select id="packCat_${p}"></select><input id="packInput_${p}" maxlength="80" placeholder="${esc(t.placeholder)}"><button id="packAdd_${p}">${esc(t.add)}</button></div><div id="packList_${p}"></div><button class="pack-restore" id="packRestore_${p}">${esc(t.restore)}</button></div>`).join('')}</div>`;
    ['ma','morita'].forEach(p=>{const sel=document.getElementById('packCat_'+p);Object.keys(t.cats).forEach(k=>{const o=document.createElement('option');o.value=k;o.textContent=t.cats[k];sel.appendChild(o)});document.getElementById('packAdd_'+p).onclick=()=>add(p);document.getElementById('packInput_'+p).onkeydown=e=>{if(e.key==='Enter')add(p)};document.getElementById('packRestore_'+p).onclick=()=>restore(p);renderPerson(p)});
    document.querySelectorAll('.dual-pack-tab').forEach(btn=>btn.onclick=()=>switchPerson(btn.dataset.person));switchPerson(activePerson(),false);
  }
  window.addEventListener('trip-sync-prep',e=>{const r=e.detail,p=r.person;if(!people[p])return;const s=state(p);s[r.item_id]=!!r.checked;write(p,'ready',s);let c=custom(p),d=deleted(p);if(r.custom_name&&!c.some(x=>x.id===r.item_id))c.push({id:r.item_id,cat:r.category||'docs',custom:true,name:r.custom_name});write(p,'custom',c);if(r.deleted){if(!d.includes(r.item_id))d.push(r.item_id)}else d=d.filter(id=>id!==r.item_id);write(p,'deleted',d);renderPerson(p)});
  window.addEventListener('load',()=>setTimeout(install,900));document.querySelectorAll('.langbtn').forEach(b=>b.addEventListener('click',()=>setTimeout(install,100)));
})();