(function(){
if((window.TRIP_VIEW||'')!=='prep')return;
const P=['ma','morita'],N={zh:{ma:'马',morita:'森田'},ja:{ma:'馬',morita:'森田'},en:{ma:'Ma',morita:'Morita'},th:{ma:'Ma',morita:'Morita'}};
const lc=()=>typeof lang!=='undefined'?lang:'zh',get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}},key=(p,t)=>`tripPrep_${p}_${t}`;
function data(p){const del=new Set(get(key(p,'del'),[]));return [...prepDefaults.filter(x=>!del.has(x.id)),...get(key(p,'custom'),[])]}
function renderPerson(p){const t=prepLang(),st=get(key(p,'ready'),{}),all=data(p),done=all.filter(x=>st[x.id]).length,box=document.getElementById('person_'+p);if(!box)return;box.innerHTML=`<div class="pp-head"><strong>${N[lc()][p]}</strong><span>${t.progress}: ${done}/${all.length}</span></div><div class="pp-bar"><i style="width:${all.length?done/all.length*100:0}%"></i></div><div class="pp-add"><select></select><input maxlength="80" placeholder="${esc(t.placeholder)}"><button>${esc(t.add)}</button></div><div class="pp-list"></div><button class="pp-reset">${esc(t.restore)}</button>`;
const sel=box.querySelector('select'),inp=box.querySelector('input');Object.keys(t.cats).forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=t.cats[c];sel.appendChild(o)});const add=()=>{const v=inp.value.trim();if(!v)return;const a=get(key(p,'custom'),[]);a.push({id:'c_'+Date.now()+Math.random(),cat:sel.value,custom:true,name:v});localStorage.setItem(key(p,'custom'),JSON.stringify(a));renderPerson(p)};box.querySelector('.pp-add button').onclick=add;inp.onkeydown=e=>{if(e.key==='Enter')add()};
const list=box.querySelector('.pp-list'),groups={};Object.keys(t.cats).forEach(c=>groups[c]=[]);all.forEach(x=>(groups[x.cat]||(groups[x.cat]=[])).push(x));Object.entries(groups).forEach(([c,a])=>{if(!a.length)return;const h=document.createElement('div');h.className='pack-category';h.textContent=t.cats[c]||c;list.appendChild(h);a.forEach(x=>{const yes=!!st[x.id],r=document.createElement('div');r.className='pack-row'+(yes?' done':'');const nm=x.custom?x.name:(x.n[lc()]||x.n.zh);r.innerHTML=`<input class="pack-check" type="checkbox" ${yes?'checked':''}><div><div class="pack-name">${esc(nm)}</div><div class="pack-status">${yes?esc(t.ready):esc(t.pending)}</div></div><button class="pack-delete">${esc(t.delete)}</button>`;r.querySelector('input').onchange=e=>{const s=get(key(p,'ready'),{});s[x.id]=e.target.checked;localStorage.setItem(key(p,'ready'),JSON.stringify(s));renderPerson(p)};r.querySelector('button').onclick=()=>{if(x.custom)localStorage.setItem(key(p,'custom'),JSON.stringify(get(key(p,'custom'),[]).filter(y=>y.id!==x.id)));else{const d=get(key(p,'del'),[]);if(!d.includes(x.id))d.push(x.id);localStorage.setItem(key(p,'del'),JSON.stringify(d))}const s=get(key(p,'ready'),{});delete s[x.id];localStorage.setItem(key(p,'ready'),JSON.stringify(s));renderPerson(p)};list.appendChild(r)})});box.querySelector('.pp-reset').onclick=()=>{if(confirm(t.confirmRestore)){['ready','custom','del'].forEach(k=>localStorage.removeItem(key(p,k)));renderPerson(p)}}}
function render(){const old=document.getElementById('packList');if(!old)return;const card=old.closest('.prep-card');if(!card)return;if(!document.getElementById('ppStyle')){const s=document.createElement('style');s.id='ppStyle';s.textContent='.pp-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.pp-card{border:1px solid #dfe6e3;border-radius:15px;padding:14px;background:#fff}.pp-head{display:flex;justify-content:space-between;align-items:center}.pp-head strong{font-size:20px}.pp-head span{font-size:12px;color:#185f57;font-weight:800}.pp-bar{height:7px;background:#e7eeeb;border-radius:99px;overflow:hidden;margin:9px 0 13px}.pp-bar i{display:block;height:100%;background:#185f57}.pp-add{display:grid;grid-template-columns:120px 1fr auto;gap:7px}.pp-add select,.pp-add input{min-width:0;border:1px solid #d3dfdb;border-radius:8px;padding:8px}.pp-add button{border:0;border-radius:8px;background:#185f57;color:#fff;font-weight:800}.pp-reset{margin-top:10px;border:1px solid #dfe6e3;background:#f7f9f8;border-radius:8px;padding:8px;color:#687570;font-weight:800}@media(max-width:900px){.pp-grid{grid-template-columns:1fr}}@media(max-width:560px){.pp-add{grid-template-columns:1fr 1fr}.pp-add input,.pp-add button{grid-column:1/-1}}';document.head.appendChild(s)}const t=prepLang();card.innerHTML=`<div class="pack-head" style="margin-bottom:12px"><div><h3>${esc(t.luggageTitle)}</h3><p>${esc(t.luggageSub)}</p></div></div><div class="pp-grid"><div class="pp-card" id="person_ma"></div><div class="pp-card" id="person_morita"></div></div>`;P.forEach(renderPerson)}
window.addEventListener('load',()=>setTimeout(render,150));document.querySelectorAll('.langbtn').forEach(b=>b.addEventListener('click',()=>setTimeout(render,80)));
})();