const RATE = 4.8;

const ui = {
 zh:{
   language:"语言", currencyLabel:"预算币种", title:"8月26–29日 · 芭提雅 & 曼谷旅行计划",
   subtitle:"26日抵达芭提雅；27日格兰岛游泳、拖曳伞和夜钓鱿鱼；28日射击、骑象后前往曼谷并参观 Jim Thompson House；29日泰服、郑王庙、卧佛寺后前往 DMK。",
   hotel:"住宿：26–27日 Garden Cliff；28日 FuramaXclusive Asoke", rate:"预算换算：฿1 ≈ ¥4.8",
   save:"预算可切换 THB/JPY；实际金额按 THB 保存在本设备", nav26:"8月26日",nav27:"8月27日",nav28:"8月28日",nav29:"8月29日",navSummary:"金额统计",
   d26:"8月26日｜抵达 & 休息", d26theme:"轻松入住 · 吃饭 · 水果",
   d27:"8月27日｜格兰岛 + 夜钓鱿鱼", d27theme:"拖曳伞 · 游泳 · Tappia",
   d28:"8月28日｜射击 + 骑象 → 曼谷", d28theme:"Grab/Bolt · 单程接送 · Jim Thompson House",
   d29:"8月29日｜泰服 + 郑王庙 + 卧佛寺", d29theme:"晚起 · 寺庙 · 拍照 · DMK",
   map:"路线地图",
   map26note:"点击每个计划后的“查看地图”可打开 Google Maps。地图连线仅作路线示意。",
   map27note:"海上连线仅作行程示意，不代表实际航线。当天船班、水上项目和海况以现场公告为准。",
   map28note:"芭提雅市内用 Grab/Bolt；跨城只订 Garden Cliff → FuramaXclusive Asoke 单程固定价接送。",
   map29note:"郑王庙 → 卧佛寺建议坐过河渡船，避免打车绕路。晚间预留充足时间前往 DMK。",
   mapBtn:"查看地图",webBtn:"查看网站",estimated:"预计金额",actual:"实际金额",actualPh:"输入",
   summary:"实际金额统计",reset:"清空实际金额",totalThb:"实际消费合计（THB）",totalJpy:"折算日元（参考）",
   filled:"已填写项目",footer:"实际金额统一输入泰铢（THB），自动按 ฿1 ≈ ¥4.8 显示参考日元。预算显示可切换 THB / JPY。数据只保存在当前浏览器。"
 },
 en:{
   language:"Language", currencyLabel:"Budget currency", title:"Aug 26–29 · Pattaya & Bangkok Trip Plan",
   subtitle:"Aug 26: arrive in Pattaya. Aug 27: Koh Larn swimming, parasailing and night squid fishing. Aug 28: shooting, elephant ride, transfer to Bangkok and Jim Thompson House. Aug 29: Thai costume, Wat Arun, Wat Pho and DMK.",
   hotel:"Stay: Aug 26–27 Garden Cliff; Aug 28 FuramaXclusive Asoke", rate:"Budget rate: ฿1 ≈ ¥4.8",
   save:"Budget display: THB/JPY; actual spending is stored in THB on this device",nav26:"Aug 26",nav27:"Aug 27",nav28:"Aug 28",nav29:"Aug 29",navSummary:"Expense Summary",
   d26:"Aug 26 | Arrival & Rest",d26theme:"Check-in · Dinner · Fruit",
   d27:"Aug 27 | Koh Larn + Squid Fishing",d27theme:"Parasailing · Swimming · Tappia",
   d28:"Aug 28 | Shooting + Elephant Ride → Bangkok",d28theme:"Grab/Bolt · One-way transfer · Jim Thompson House",
   d29:"Aug 29 | Thai Costume + Wat Arun + Wat Pho",d29theme:"Late start · Temples · Photos · DMK",
   map:"Route Map",
   map26note:"Use “View Map” after each item to open Google Maps. Lines are route illustrations only.",
   map27note:"Sea lines are illustrative, not exact ferry routes. Check same-day ferry, water activities and sea conditions.",
   map28note:"Use Grab/Bolt within Pattaya; book only Garden Cliff → FuramaXclusive Asoke as a fixed-price one-way transfer.",
   map29note:"Use the cross-river ferry from Wat Arun to Wat Pho to avoid a long taxi detour. Leave ample time for DMK in the evening.",
   mapBtn:"View Map",webBtn:"Website",estimated:"Estimated",actual:"Actual",actualPh:"Enter",
   summary:"Actual Expense Summary",reset:"Clear Actuals",totalThb:"Actual total (THB)",totalJpy:"JPY equivalent (reference)",
   filled:"Items entered",footer:"Enter actual spending in THB. JPY is calculated at ฿1 ≈ ¥4.8. Budget display can switch between THB and JPY. Data is stored only in this browser."
 },
 ja:{
   language:"言語", currencyLabel:"予算通貨", title:"8月26–29日 · パタヤ＆バンコク旅行プラン",
   subtitle:"26日はパタヤ到着。27日はラン島で海水浴・パラセーリング・夜のイカ釣り。28日は射撃・象乗りの後バンコクへ移動しJim Thompson House。29日はタイ衣装、ワット・アルン、ワット・ポー、DMKへ。",
   hotel:"宿泊：26–27日 Garden Cliff；28日 FuramaXclusive Asoke", rate:"予算換算：฿1 ≈ ¥4.8",
   save:"予算表示はTHB/JPY切替；実際金額はTHBで端末に保存",nav26:"8月26日",nav27:"8月27日",nav28:"8月28日",nav29:"8月29日",navSummary:"金額集計",
   d26:"8月26日｜到着・休憩",d26theme:"チェックイン · 夕食 · フルーツ",
   d27:"8月27日｜ラン島 + 夜のイカ釣り",d27theme:"パラセーリング · 海水浴 · Tappia",
   d28:"8月28日｜射撃 + 象乗り → バンコク",d28theme:"Grab/Bolt · 片道送迎 · Jim Thompson House",
   d29:"8月29日｜タイ衣装 + ワット・アルン + ワット・ポー",d29theme:"ゆっくり開始 · 寺院 · 写真 · DMK",
   map:"ルートマップ",
   map26note:"各予定の「地図を見る」からGoogle Mapsを開けます。線はルートの目安です。",
   map27note:"海上の線は行程イメージです。当日の船便・水上アクティビティ・海況を確認してください。",
   map28note:"パタヤ市内はGrab/Bolt。長距離はGarden Cliff → FuramaXclusive Asokeの固定料金片道送迎のみ予約。",
   map29note:"ワット・アルン→ワット・ポーは渡し船が便利。夜はDMKへの移動時間を十分確保。",
   mapBtn:"地図を見る",webBtn:"サイトを見る",estimated:"予想金額",actual:"実際金額",actualPh:"入力",
   summary:"実際金額の集計",reset:"実際金額をクリア",totalThb:"実際支出合計（THB）",totalJpy:"日本円換算（参考）",
   filled:"入力済み項目",footer:"実際金額はTHBで入力し、฿1 ≈ ¥4.8で参考円を表示します。予算表示はTHB/JPY切替可能。データはこのブラウザ内のみ保存されます。"
 },
 th:{
   language:"ภาษา", currencyLabel:"สกุลงบประมาณ", title:"แผนเที่ยวพัทยาและกรุงเทพฯ 26–29 สิงหาคม",
   subtitle:"26 ส.ค. ถึงพัทยา; 27 ส.ค. เกาะล้าน ว่ายน้ำ พาราเซลลิ่ง และตกหมึก; 28 ส.ค. ยิงปืน ขี่ช้าง แล้วไปกรุงเทพฯ และ Jim Thompson House; 29 ส.ค. ชุดไทย วัดอรุณ วัดโพธิ์ และไป DMK",
   hotel:"ที่พัก: 26–27 Garden Cliff; 28 FuramaXclusive Asoke", rate:"อัตรางบประมาณ: ฿1 ≈ ¥4.8",
   save:"งบประมาณสลับ THB/JPY ได้; ค่าใช้จ่ายจริงบันทึกเป็น THB ในอุปกรณ์นี้",nav26:"26 ส.ค.",nav27:"27 ส.ค.",nav28:"28 ส.ค.",nav29:"29 ส.ค.",navSummary:"สรุปค่าใช้จ่าย",
   d26:"26 ส.ค. | เดินทางถึงและพักผ่อน",d26theme:"เช็กอิน · อาหารเย็น · ผลไม้",
   d27:"27 ส.ค. | เกาะล้าน + ตกหมึกกลางคืน",d27theme:"พาราเซลลิ่ง · ว่ายน้ำ · Tappia",
   d28:"28 ส.ค. | ยิงปืน + ขี่ช้าง → กรุงเทพฯ",d28theme:"Grab/Bolt · รถเที่ยวเดียว · Jim Thompson House",
   d29:"29 ส.ค. | ชุดไทย + วัดอรุณ + วัดโพธิ์",d29theme:"เริ่มสาย · วัด · ถ่ายรูป · DMK",
   map:"แผนที่เส้นทาง",
   map26note:"กด “ดูแผนที่” หลังแต่ละรายการเพื่อเปิด Google Maps เส้นทางบนแผนที่เป็นเพียงภาพประกอบ",
   map27note:"เส้นทางทางทะเลเป็นภาพประกอบ กรุณาตรวจสอบเรือ กิจกรรมทางน้ำ และสภาพทะเลในวันเดินทาง",
   map28note:"ในพัทยาใช้ Grab/Bolt; ข้ามเมืองจองเฉพาะ Garden Cliff → FuramaXclusive Asoke แบบราคาเหมาจ่ายเที่ยวเดียว",
   map29note:"จากวัดอรุณไปวัดโพธิ์ใช้เรือข้ามฟากสะดวกกว่าอ้อมรถ และเผื่อเวลาไป DMK ตอนเย็น",
   mapBtn:"ดูแผนที่",webBtn:"ดูเว็บไซต์",estimated:"ประมาณการ",actual:"จ่ายจริง",actualPh:"กรอก",
   summary:"สรุปค่าใช้จ่ายจริง",reset:"ล้างยอดจริง",totalThb:"ยอดใช้จ่ายจริง (THB)",totalJpy:"เทียบเป็นเยน (อ้างอิง)",
   filled:"รายการที่กรอกแล้ว",footer:"กรอกค่าใช้จ่ายจริงเป็น THB ระบบคำนวณเยนที่ ฿1 ≈ ¥4.8 งบประมาณสลับ THB/JPY ได้ ข้อมูลบันทึกเฉพาะในเบราว์เซอร์นี้"
 }
};
